@extends('layouts.bendahara')

@section('title', 'Dashboard Bendahara')
@section('page_title', 'Dashboard Bendahara')

@section('content')
@php
    $routePrefix = 'bendahara.';
    $rupiah = fn ($value) => 'Rp '.number_format((float) $value, 0, ',', '.');
@endphp
<style>
.finance-dashboard{max-width:1360px;font-family:'DM Sans',system-ui,sans-serif}.finance-dashboard h2,.finance-dashboard h3,.finance-value,.finance-action{font-family:'Plus Jakarta Sans',system-ui,sans-serif}.finance-hero{background:linear-gradient(118deg,#6d3900,#ad6007 52%,#d98e1f)}.finance-dashboard .finance-hero h2{color:#fff!important}.finance-dashboard .finance-hero p{color:rgb(255 255 255 / .88)!important}.finance-dashboard .finance-hero p:first-child{color:#ffecbd!important}.finance-card{border:1px solid #f0dfc4;background:#fff;box-shadow:0 10px 24px rgb(92 49 3 / .05)}.finance-kpi{min-height:146px}.finance-icon{display:grid;height:40px;width:40px;place-items:center;border-radius:14px;font-weight:900}.finance-pending+ .finance-pending{border-top:1px solid #f2e5d1}.finance-chart-scroll{overflow:hidden}.finance-chart{display:grid;width:100%;grid-template-columns:repeat({{ max(1, $monthlyReceipts->count()) }},minmax(0,1fr));align-items:end;gap:7px;height:218px}.finance-chart-item{display:flex;height:100%;min-width:0;flex-direction:column;justify-content:end;gap:7px}.finance-chart-bar{min-height:8px;border-radius:10px 10px 4px 4px;background:linear-gradient(180deg,#fbbf24,#bf6508);box-shadow:0 8px 16px rgb(180 98 0 / .17)}.finance-chart-value{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:center}.finance-table td{border-bottom:1px solid #edf1f6}.finance-table tr:last-child td{border-bottom:0}.finance-dashboard .finance-overview{grid-template-columns:minmax(0,1fr)!important}@media(min-width:1024px){.finance-dashboard .finance-overview{grid-template-columns:minmax(0,1.55fr) minmax(310px,.85fr)!important}}@media(max-width:1023px){.finance-dashboard .finance-overview{display:flex!important;flex-direction:column!important}.finance-dashboard .finance-overview>aside{width:100%}}@media(max-width:640px){.finance-hero{border-radius:20px;padding:18px!important}.finance-hero>div{gap:14px}.finance-dashboard .finance-hero p:first-child{font-size:10px}.finance-dashboard .finance-hero h2{margin-top:5px;font-size:20px;line-height:1.25}.finance-dashboard .finance-hero p:not(:first-child){display:none}.finance-hero .finance-action{padding:10px 12px;font-size:12px}.finance-kpi{min-height:0}.finance-table{min-width:620px}.finance-chart{height:166px;gap:4px}.finance-chart-item{gap:5px}.finance-chart-item p{font-size:9px!important}.finance-chart-bar{border-radius:7px 7px 3px 3px}}
@media(min-width:1024px){.finance-dashboard .finance-overview{display:flex!important;flex-direction:column!important}.finance-dashboard .finance-overview>aside{width:100%}}
</style>
<style>
    .finance-chart { gap: 12px; }
    .finance-chart-bar { margin-inline: 3px; }

    @media (max-width: 640px) {
        .finance-chart { gap: 7px; }
        .finance-chart-bar { margin-inline: 1px; }
    }
</style>
<div class="finance-dashboard mx-auto space-y-5">
    <section class="finance-hero rounded-3xl px-5 py-6 text-white shadow-lg shadow-amber-900/15 md:px-7 md:py-7">
        <div class="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-amber-100">Keuangan SPMB{{ $activeAcademicYear?->name ? ' · '.$activeAcademicYear->name : '' }}</p><h2 class="mt-2 text-2xl font-black tracking-tight md:text-3xl">Selamat datang, {{ Auth::user()->name ?? 'Bendahara' }}</h2><p class="mt-2 max-w-xl text-sm font-semibold leading-6 text-amber-50/90">Pantau dana masuk dan tindak lanjuti pembayaran yang perlu diperiksa.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route($routePrefix.'pembayaran.index') }}" class="finance-action inline-flex items-center justify-center rounded-xl bg-white px-4 py-3 text-sm font-black text-amber-900">Kelola pembayaran &rarr;</a><a href="{{ route($routePrefix.'laporan.index') }}" class="finance-action inline-flex items-center justify-center rounded-xl border border-white/35 px-4 py-3 text-sm font-black text-white">Laporan</a></div></div>
    </section>

    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <article class="finance-card finance-kpi rounded-2xl p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.12em] text-slate-500">Dana terverifikasi</p><p class="finance-value mt-3 text-2xl font-black tracking-tight text-slate-950">{{ $rupiah($verifiedTotal) }}</p></div><span class="finance-icon bg-emerald-50 text-emerald-700">Rp</span></div><p class="mt-3 text-xs font-bold text-slate-500">Akumulasi pembayaran diterima</p></article>
        <article class="finance-card finance-kpi rounded-2xl p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.12em] text-slate-500">Masuk hari ini</p><p class="finance-value mt-3 text-2xl font-black tracking-tight text-slate-950">{{ $rupiah($todayVerifiedTotal) }}</p></div><span class="finance-icon bg-sky-50 text-sky-700">&#8599;</span></div><p class="mt-3 text-xs font-bold text-slate-500">{{ $todayTransactionCount }} transaksi terverifikasi</p></article>
        <a href="{{ route($routePrefix.'pembayaran.index', ['transaction_status' => 'pending']) }}" class="finance-card finance-kpi rounded-2xl p-5 transition hover:-translate-y-0.5 hover:border-amber-300"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.12em] text-slate-500">Perlu diperiksa</p><p class="finance-value mt-3 text-3xl font-black tracking-tight text-amber-700">{{ $pendingVerificationCount }}</p></div><span class="finance-icon bg-amber-50 text-amber-700">!</span></div><p class="mt-3 text-xs font-bold text-amber-700">Bukti pembayaran menunggu verifikasi</p></a>
        <a href="{{ route($routePrefix.'pembayaran.index', ['bill_status' => 'unpaid']) }}" class="finance-card finance-kpi rounded-2xl p-5 transition hover:-translate-y-0.5 hover:border-rose-300"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.12em] text-slate-500">Belum dibayar</p><p class="finance-value mt-3 text-3xl font-black tracking-tight text-rose-600">{{ $unpaidBills }}</p></div><span class="finance-icon bg-rose-50 text-rose-600">-</span></div><p class="mt-3 text-xs font-bold text-slate-500">Tagihan tanpa pembayaran masuk</p></a>
    </section>

    <section class="finance-overview grid gap-5">
        <article class="finance-card overflow-hidden rounded-3xl"><header class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-5 md:px-6"><div><p class="text-xs font-black uppercase tracking-[.14em] text-amber-700">Grafik penerimaan</p><h3 class="mt-1 text-lg font-black text-slate-900">Dana masuk per bulan</h3></div><span class="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-black text-amber-800">{{ $chartPeriodLabel }}</span></header><div class="p-5 md:p-6"><div class="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p class="text-2xl font-black tracking-tight text-slate-950">{{ $rupiah($monthlyReceipts->sum('total')) }}</p><p class="mt-1 text-sm font-semibold text-slate-500">{{ $chartUsesRecordedMonths ? 'Pembayaran tercatat menurut bulan' : 'Penerimaan selama tahun ajaran aktif' }}</p></div><a href="{{ route($routePrefix.'laporan.index') }}" class="text-sm font-black text-amber-700">Lihat laporan &rarr;</a></div><div class="mb-4 grid grid-cols-2 gap-3"><div class="rounded-2xl bg-amber-50 p-3"><p class="text-[11px] font-black uppercase tracking-wide text-amber-800">Pembayaran formulir</p><p class="mt-1 text-lg font-black text-amber-950">{{ $rupiah($registrationVerifiedTotal) }}</p><p class="mt-1 text-xs font-bold text-amber-800">{{ $registrationPayerCount }} peserta membayar</p></div><div class="rounded-2xl bg-orange-50 p-3"><p class="text-[11px] font-black uppercase tracking-wide text-orange-800">Pembayaran daftar ulang</p><p class="mt-1 text-lg font-black text-orange-950">{{ $rupiah($reRegistrationVerifiedTotal) }}</p><p class="mt-1 text-xs font-bold text-orange-800">{{ $reRegistrationPayerCount }} peserta membayar</p></div></div><div class="finance-chart-scroll rounded-2xl bg-slate-50 px-4 pb-3 pt-5"><div class="finance-chart">@foreach($monthlyReceipts as $receipt)@php($height = max(8, round(($receipt['total'] / $monthlyReceiptMax) * 100)))<div class="finance-chart-item" title="{{ $receipt['date'] }} · {{ $rupiah($receipt['total']) }}"><p class="finance-chart-value text-[10px] font-black text-slate-500">{{ $receipt['total'] > 0 ? number_format($receipt['total'] / 1000, 0, ',', '.') . 'k' : '-' }}</p><div class="h-px bg-slate-200"></div><div class="finance-chart-bar" style="height:{{ $height }}%"></div><p class="finance-chart-value text-xs font-black text-slate-600">{{ $receipt['label'] }}</p></div>@endforeach</div></div></div></article>
        <aside class="finance-card rounded-3xl p-5 md:p-6"><div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-[.14em] text-amber-700">Tindak lanjut</p><h3 class="mt-1 text-lg font-black text-slate-900">Menunggu verifikasi</h3></div><a href="{{ route($routePrefix.'pembayaran.index', ['transaction_status' => 'pending']) }}" class="text-xs font-black text-amber-700">Lihat semua &rarr;</a></div><div class="mt-4">@forelse($pendingTransactions as $transaction)@php($name = $transaction->tagihan?->pendaftar?->biodata?->full_name ?? $transaction->tagihan?->pendaftar?->user?->name ?? 'Peserta')<article class="finance-pending flex items-center justify-between gap-3 py-3"><div class="min-w-0"><p class="truncate text-sm font-black text-slate-900">{{ $name }}</p><p class="mt-0.5 truncate text-xs font-semibold text-slate-500">{{ $transaction->tagihan?->jenisTagihan?->name ?? 'Tagihan SPMB' }}</p></div><strong class="shrink-0 text-sm text-amber-800">{{ $rupiah($transaction->amount) }}</strong></article>@empty<p class="rounded-2xl bg-emerald-50 px-4 py-5 text-center text-sm font-bold text-emerald-800">Tidak ada pembayaran yang perlu diperiksa.</p>@endforelse</div></aside>
    </section>

    <section class="finance-card overflow-hidden rounded-3xl"><header class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-5 md:px-6"><div><p class="text-xs font-black uppercase tracking-[.14em] text-slate-500">Aktivitas terakhir</p><h3 class="mt-1 text-lg font-black text-slate-900">Pembayaran terbaru</h3></div><a href="{{ route($routePrefix.'pembayaran.index') }}" class="rounded-xl border border-amber-200 px-3 py-2 text-xs font-black text-amber-800">Buka pembayaran</a></header><div class="overflow-x-auto"><table class="finance-table w-full min-w-[640px] text-left"><thead class="bg-slate-50 text-[11px] font-black uppercase tracking-[.1em] text-slate-500"><tr><th class="px-5 py-3 md:px-6">Peserta</th><th class="px-5 py-3">Tagihan</th><th class="px-5 py-3">Metode</th><th class="px-5 py-3">Waktu</th><th class="px-5 py-3 text-right md:px-6">Nominal</th></tr></thead><tbody>@forelse($recentTransactions as $transaction)@php($name = $transaction->tagihan?->pendaftar?->biodata?->full_name ?? $transaction->tagihan?->pendaftar?->user?->name ?? 'Peserta')<tr><td class="px-5 py-4 md:px-6"><p class="font-black text-slate-900">{{ $name }}</p><p class="mt-0.5 text-xs font-semibold text-slate-500">{{ $transaction->tagihan?->pendaftar?->registration_number ?? '-' }}</p></td><td class="px-5 py-4 text-sm font-semibold text-slate-700">{{ $transaction->tagihan?->jenisTagihan?->name ?? 'Tagihan SPMB' }}</td><td class="px-5 py-4 text-sm font-semibold text-slate-600">{{ $transaction->payment_method === 'cash' ? 'Tunai' : ($transaction->payment_method === 'transfer' ? 'Transfer' : 'Digital') }}</td><td class="px-5 py-4 text-sm font-semibold text-slate-500">{{ $transaction->payment_date ? \Illuminate\Support\Carbon::parse($transaction->payment_date)->translatedFormat('d M Y, H:i') : '-' }}</td><td class="px-5 py-4 text-right font-black text-emerald-700 md:px-6">{{ $rupiah($transaction->amount) }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-sm font-bold text-slate-400">Belum ada pembayaran terverifikasi.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
