<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DatabaseBackupController;
use App\Http\Controllers\Admin\PeriodArchiveController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PengaturanController;
use App\Http\Controllers\Admin\JurusanController;
use App\Http\Controllers\Admin\GelombangController;
use App\Http\Controllers\Admin\SiswaController;
use App\Http\Controllers\Admin\ReferensiSekolahController;
use App\Http\Controllers\Admin\MasterDropdownController;
use App\Http\Controllers\Admin\BeritaLandingController;
use App\Http\Controllers\Bendahara\LaporanController as BendaharaLaporanController;
use App\Http\Controllers\Bendahara\PembayaranController as BendaharaPembayaranController;
use App\Http\Controllers\Bendahara\RekeningController as BendaharaRekeningController;
use App\Http\Controllers\Bendahara\TagihanController as BendaharaTagihanController;
use App\Http\Controllers\Panitia\LayananPiketController as PanitiaLayananPiketController;
use App\Http\Controllers\Panitia\PendaftarController as PanitiaPendaftarController;
use App\Http\Controllers\Panitia\AssistedRegistrationController;
use App\Http\Controllers\Panitia\SeleksiController as PanitiaSeleksiController;
use App\Http\Controllers\Panitia\TesSpmbController as PanitiaTesSpmbController;
use App\Http\Controllers\Panitia\VerifikasiBerkasController as PanitiaVerifikasiBerkasController;
use App\Http\Controllers\Shared\HasilTesController;
use App\Http\Controllers\Shared\ExecutiveReportController;
use Illuminate\Support\Facades\Route;

Route::middleware(['web', 'admin'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/laporan-eksekutif', [ExecutiveReportController::class, 'index'])->name('laporan-eksekutif.index');
    Route::get('/laporan-eksekutif/pdf', [ExecutiveReportController::class, 'pdf'])->name('laporan-eksekutif.pdf');
    Route::get('/laporan-eksekutif/excel', [ExecutiveReportController::class, 'exportExcel'])->name('laporan-eksekutif.excel');
    Route::get('/log-aktivitas', [DashboardController::class, 'activityLog'])->name('activity-log.index');
    Route::get('/users', [UserController::class, 'index'])->name('users.index');
    Route::post('/users/guru', [UserController::class, 'storeTeacher'])->name('users.guru.store');
    Route::patch('/users/{user}', [UserController::class, 'update'])->name('users.update');
    Route::patch('/users/{user}/phone', [UserController::class, 'updatePhone'])->name('users.phone.update');
    Route::delete('/users/{user}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::get('/siswa', [SiswaController::class, 'index'])->name('siswa.index');
    Route::get('/master/asal-sekolah', [ReferensiSekolahController::class, 'index'])->name('master.sekolah.index');
    Route::get('/master/asal-sekolah/cari', [ReferensiSekolahController::class, 'search'])->name('master.sekolah.search');
    Route::post('/master/asal-sekolah', [ReferensiSekolahController::class, 'store'])->name('master.sekolah.store');
    Route::put('/master/asal-sekolah/{sekolah}', [ReferensiSekolahController::class, 'update'])->name('master.sekolah.update');
    Route::delete('/master/asal-sekolah/{sekolah}', [ReferensiSekolahController::class, 'destroy'])->name('master.sekolah.destroy');
    Route::get('/master/dropdown', [MasterDropdownController::class, 'index'])->name('master.dropdown.index');
    Route::post('/master/dropdown/{table}', [MasterDropdownController::class, 'store'])->name('master.dropdown.store');
    Route::put('/master/dropdown/{table}/{id}', [MasterDropdownController::class, 'update'])->name('master.dropdown.update');
    Route::delete('/master/dropdown/{table}/{id}', [MasterDropdownController::class, 'destroy'])->name('master.dropdown.destroy');
    Route::get('/master/agama', [MasterDropdownController::class, 'page'])->defaults('table', 'agama')->name('master.agama.index');
    Route::get('/master/pekerjaan', [MasterDropdownController::class, 'page'])->defaults('table', 'pekerjaan')->name('master.pekerjaan.index');
    Route::get('/master/pendidikan', [MasterDropdownController::class, 'page'])->defaults('table', 'pendidikan')->name('master.pendidikan.index');
    Route::get('/master/penghasilan', [MasterDropdownController::class, 'page'])->defaults('table', 'penghasilan')->name('master.penghasilan.index');
    Route::get('/master/jalur-pendaftaran', [MasterDropdownController::class, 'page'])->defaults('table', 'jalur_pendaftaran')->name('master.jalur-pendaftaran.index');
    Route::patch('/siswa/{pendaftar}/login', [SiswaController::class, 'updateLogin'])->name('siswa.login.update');

    Route::get('/pendaftar', [PanitiaPendaftarController::class, 'index'])->name('pendaftar.index');
    Route::get('/pendaftaran-dibantu', [AssistedRegistrationController::class, 'create'])->name('pendaftaran_bantuan.create');
    Route::get('/pendaftaran-dibantu/cari-sekolah', [AssistedRegistrationController::class, 'searchSchool'])->name('pendaftaran_bantuan.sekolah.search');
    Route::post('/pendaftaran-dibantu', [AssistedRegistrationController::class, 'store'])->name('pendaftaran_bantuan.store');
    Route::get('/pendaftaran-dibantu/{pendaftar}/edit', [AssistedRegistrationController::class, 'edit'])->name('pendaftaran_bantuan.edit');
    Route::put('/pendaftaran-dibantu/{pendaftar}', [AssistedRegistrationController::class, 'update'])->name('pendaftaran_bantuan.update');
    Route::get('/pendaftar/export-excel', [PanitiaPendaftarController::class, 'export'])->name('pendaftar.export');
    Route::get('/pendaftar/{pendaftar}', [PanitiaPendaftarController::class, 'show'])->name('pendaftar.show');
    Route::get('/pendaftar/{pendaftar}/cetak', [PanitiaPendaftarController::class, 'cetak'])->name('pendaftar.cetak');
    Route::get('/pendaftar/{pendaftar}/pdf', [PanitiaPendaftarController::class, 'pdf'])->name('pendaftar.pdf');
    Route::put('/pendaftar/{pendaftar}/verifikasi', [PanitiaPendaftarController::class, 'verify'])->name('pendaftar.verify');
    Route::get('/verifikasi', [PanitiaVerifikasiBerkasController::class, 'index'])->name('verifikasi.index');
    Route::get('/verifikasi/{pendaftar}', [PanitiaVerifikasiBerkasController::class, 'show'])->name('verifikasi.show');
    Route::put('/verifikasi/dokumen/{dokumen}', [PanitiaVerifikasiBerkasController::class, 'verify'])->name('verifikasi.verify');
    Route::get('/dokumen/{dokumen}/lihat', [PanitiaVerifikasiBerkasController::class, 'viewDocument'])->name('dokumen.show');
    Route::redirect('/tes-spmb', '/admin/tes-spmb/btq')->name('tes.index');
    Route::get('/hasil-tes', [HasilTesController::class, 'index'])->name('hasil-tes.index');
    Route::get('/hasil-tes/{pendaftar}', [HasilTesController::class, 'show'])->name('hasil-tes.show');
    Route::get('/tes-spmb/cbt/template', [PanitiaTesSpmbController::class, 'downloadCbtTemplate'])->name('tes.cbt-template');
    Route::get('/tes-spmb/cbt/export', [PanitiaTesSpmbController::class, 'exportCbtQuestions'])->name('tes.cbt-export');
    Route::post('/tes-spmb/cbt/import', [PanitiaTesSpmbController::class, 'importCbtQuestions'])->name('tes.cbt-import');
    Route::post('/tes-spmb/cbt/open-bulk', [PanitiaTesSpmbController::class, 'openCbtAccessBulk'])->name('tes.cbt.open-bulk');
    Route::post('/tes-spmb/cbt/pertanyaan', [PanitiaTesSpmbController::class, 'storeCbtQuestion'])->name('tes.cbt-question.store');
    Route::delete('/tes-spmb/cbt/pertanyaan/{question}', [PanitiaTesSpmbController::class, 'destroyCbtQuestion'])->name('tes.cbt-question.destroy');
    Route::post('/tes-spmb/wawancara/pertanyaan', [PanitiaTesSpmbController::class, 'storeInterviewQuestion'])->name('tes.interview-question.store');
    Route::patch('/tes-spmb/wawancara/pertanyaan/{question}', [PanitiaTesSpmbController::class, 'updateInterviewQuestion'])->name('tes.interview-question.update');
    Route::delete('/tes-spmb/wawancara/pertanyaan/{question}', [PanitiaTesSpmbController::class, 'destroyInterviewQuestion'])->name('tes.interview-question.destroy');
    Route::get('/tes-spmb/btq', [PanitiaTesSpmbController::class, 'btq'])->name('tes.btq');
    Route::get('/tes-spmb/seragam', [PanitiaTesSpmbController::class, 'uniform'])->name('tes.uniform');
    Route::get('/tes-spmb/kesehatan', [PanitiaTesSpmbController::class, 'health'])->name('tes.health');
    Route::get('/tes-spmb/cbt', [PanitiaTesSpmbController::class, 'cbt'])->name('tes.cbt');
    Route::get('/tes-spmb/wawancara', [PanitiaTesSpmbController::class, 'interview'])->name('tes.interview');
    Route::post('/tes-spmb/{pendaftar}/hasil', [PanitiaTesSpmbController::class, 'storeResult'])->name('tes.hasil.store');
    Route::post('/tes-spmb/{pendaftar}/seragam', [PanitiaTesSpmbController::class, 'storeUniform'])->name('tes.seragam.store');
    Route::post('/tes-spmb/{pendaftar}/kesehatan', [PanitiaTesSpmbController::class, 'storeHealth'])->name('tes.kesehatan.store');
    Route::post('/tes-spmb/{pendaftar}/cbt/open', [PanitiaTesSpmbController::class, 'openCbtAccess'])->name('tes.cbt.open');
    Route::post('/tes-spmb/{pendaftar}/cbt/close', [PanitiaTesSpmbController::class, 'closeCbtAccess'])->name('tes.cbt.close');
    Route::delete('/tes-spmb/{pendaftar}/hasil/{testKey}', [PanitiaTesSpmbController::class, 'destroyResult'])->name('tes.hasil.destroy');
    Route::get('/seleksi', [PanitiaSeleksiController::class, 'index'])->name('seleksi.index');
    Route::put('/seleksi/{pendaftar}', [PanitiaSeleksiController::class, 'decide'])->name('seleksi.decide');
    Route::get('/kunjungan', [PanitiaLayananPiketController::class, 'index'])->name('kunjungan.index');
    Route::get('/kunjungan/cari-sekolah', [PanitiaLayananPiketController::class, 'searchSchool'])->name('kunjungan.sekolah.search');
    Route::post('/kunjungan', [PanitiaLayananPiketController::class, 'store'])->name('kunjungan.store');

    Route::get('/tagihan', [BendaharaTagihanController::class, 'index'])->name('tagihan.index');
    Route::get('/tagihan/{bill}/invoice', [BendaharaTagihanController::class, 'invoice'])->name('tagihan.invoice');
    Route::get('/pembayaran', [BendaharaPembayaranController::class, 'index'])->name('pembayaran.index');
    Route::post('/pembayaran', [BendaharaPembayaranController::class, 'store'])->name('pembayaran.store');
    Route::patch('/pembayaran/transaksi/{transaksi}', [BendaharaPembayaranController::class, 'verify'])->name('pembayaran.verify');
    Route::get('/pembayaran/transaksi/{transaksi}/nota', [BendaharaPembayaranController::class, 'receipt'])->name('pembayaran.receipt');
    Route::get('/pembayaran/transaksi/{transaksi}/bukti', [BendaharaPembayaranController::class, 'viewProof'])->name('pembayaran.proof');
    Route::get('/rekening', [BendaharaRekeningController::class, 'index'])->name('rekening.index');
    Route::post('/rekening', [BendaharaRekeningController::class, 'store'])->name('rekening.store');
    Route::patch('/rekening/{rekening}', [BendaharaRekeningController::class, 'update'])->name('rekening.update');
    Route::patch('/rekening/{rekening}/toggle', [BendaharaRekeningController::class, 'toggle'])->name('rekening.toggle');
    Route::delete('/rekening/{rekening}', [BendaharaRekeningController::class, 'destroy'])->name('rekening.destroy');
    Route::get('/laporan', [BendaharaLaporanController::class, 'index'])->name('laporan.index');
    Route::get('/laporan/cetak', [BendaharaLaporanController::class, 'print'])->name('laporan.print');
    Route::get('/laporan/pdf', [BendaharaLaporanController::class, 'pdf'])->name('laporan.pdf');
    Route::get('/laporan/export-csv', [BendaharaLaporanController::class, 'exportCsv'])->name('laporan.export-csv');
    Route::get('/event-promo', [PengaturanController::class, 'eventPromo'])->name('event.index');
    Route::post('/event-promo', [PengaturanController::class, 'storeEventPromo'])->name('event.store');
    Route::put('/event-promo/{id}', [PengaturanController::class, 'updateEventPromo'])->name('event.update');
    Route::delete('/event-promo/{id}', [PengaturanController::class, 'destroyEventPromo'])->name('event.destroy');
    Route::get('/biaya-jurusan', [GelombangController::class, 'biayaJurusan'])->name('biaya-jurusan.index');
    Route::post('/biaya-jurusan', [GelombangController::class, 'saveBiayaJurusan'])->name('biaya-jurusan.save');
    Route::get('/biaya-jurusan/excel', [GelombangController::class, 'exportBiayaJurusan'])->name('biaya-jurusan.export');
    Route::get('/biaya-jurusan/template-excel', [GelombangController::class, 'templateBiayaJurusan'])->name('biaya-jurusan.template');
    Route::post('/biaya-jurusan/import-excel', [GelombangController::class, 'importBiayaJurusan'])->name('biaya-jurusan.import');

    Route::resource('jurusan', JurusanController::class)->except(['show']);
    Route::get('/gelombang', [GelombangController::class, 'index'])->name('gelombang.index');
    Route::post('/gelombang', [GelombangController::class, 'store'])->name('gelombang.store');
    Route::put('/gelombang/{gelombang}', [GelombangController::class, 'update'])->name('gelombang.update');
    Route::delete('/gelombang/{gelombang}', [GelombangController::class, 'destroy'])->name('gelombang.destroy');
    Route::get('/arsip-periode', [PeriodArchiveController::class, 'index'])->name('arsip-periode.index');
    Route::post('/arsip-periode/{tahunAjaran}', [PeriodArchiveController::class, 'archive'])->name('arsip-periode.archive');
    Route::post('/arsip-periode/{tahunAjaran}/buka', [PeriodArchiveController::class, 'restore'])->name('arsip-periode.restore');
    Route::get('/backup-database', [DatabaseBackupController::class, 'index'])->name('database-backup.index');
    Route::get('/backup-database/unduh', [DatabaseBackupController::class, 'download'])->name('database-backup.download');
    Route::post('/backup-database/pulihkan', [DatabaseBackupController::class, 'restore'])->name('database-backup.restore');
    Route::get('/pengaturan', fn () => redirect()->route('admin.konfigurasi.index'))->name('pengaturan.index');
    Route::post('/konfigurasi-spmb/tahun-ajaran', [PengaturanController::class, 'storeTahunAjaran'])->name('konfigurasi.tahun-ajaran.store');
    Route::get('/informasi-tes', [PengaturanController::class, 'informasiTes'])->name('informasi-tes.index');
    Route::post('/informasi-tes/persiapan', [PengaturanController::class, 'saveTestPreparation'])->name('informasi-tes.preparation.save');
    Route::post('/informasi-tes', [PengaturanController::class, 'storeInformasiTes'])->name('informasi-tes.store');
    Route::put('/informasi-tes/{jadwalSpmb}', [PengaturanController::class, 'updateInformasiTes'])->name('informasi-tes.update');
    Route::delete('/informasi-tes/{jadwalSpmb}', [PengaturanController::class, 'destroyInformasiTes'])->name('informasi-tes.destroy');
    Route::get('/konfigurasi-spmb', [PengaturanController::class, 'konfigurasi'])->name('konfigurasi.index');
    Route::post('/konfigurasi-spmb', [PengaturanController::class, 'saveKonfigurasi'])->name('konfigurasi.save');
    Route::get('/keuangan/biaya-pendaftaran', [PengaturanController::class, 'biayaPendaftaran'])->name('keuangan.biaya-pendaftaran.index');
    Route::post('/keuangan/biaya-pendaftaran', [PengaturanController::class, 'saveBiayaPendaftaran'])->name('keuangan.biaya-pendaftaran.save');
    Route::get('/identitas-sekolah', [PengaturanController::class, 'identitas'])->name('identitas.index');
    Route::post('/identitas-sekolah', [PengaturanController::class, 'saveIdentitas'])->name('identitas.save');
    Route::get('/kelola-formulir', [PengaturanController::class, 'formulir'])->name('formulir.index');
    Route::post('/kelola-formulir', [PengaturanController::class, 'saveFormulir'])->name('formulir.save');
    Route::post('/kelola-formulir/tambah', [PengaturanController::class, 'storeFormField'])->name('formulir.custom.store');
    Route::put('/kelola-formulir/{key}', [PengaturanController::class, 'updateFormField'])->name('formulir.custom.update');
    Route::delete('/kelola-formulir/{key}', [PengaturanController::class, 'destroyFormField'])->name('formulir.custom.destroy');
    Route::get('/landing-page', [PengaturanController::class, 'landing'])->name('landing.index');
    Route::post('/landing-page', [PengaturanController::class, 'saveLanding'])->name('landing.save');
    Route::get('/berita-landing', [BeritaLandingController::class, 'index'])->name('berita-landing.index');
    Route::get('/berita-landing/buat', [BeritaLandingController::class, 'create'])->name('berita-landing.create');
    Route::post('/berita-landing', [BeritaLandingController::class, 'store'])->name('berita-landing.store');
    Route::get('/berita-landing/{berita}/ubah', [BeritaLandingController::class, 'edit'])->name('berita-landing.edit');
    Route::put('/berita-landing/{berita}', [BeritaLandingController::class, 'update'])->name('berita-landing.update');
    Route::delete('/berita-landing/{berita}', [BeritaLandingController::class, 'destroy'])->name('berita-landing.destroy');
});
