@extends(request()->routeIs('admin.*') ? 'layouts.admin' : 'layouts.panitia')

@section('title', 'Approve Pembayaran')
@section('page_title', 'Approve Pembayaran')

@section('content')
    @php($canRecordPayment = auth()->user()?->hasRole('panitia') || auth()->user()?->hasRole('admin'))
    <div class="payment-review mx-auto max-w-[1360px]">
        @if($canRecordPayment)
        <div class="mb-6" x-data="paymentEntry({ candidates: @js($visits->map(fn ($visit) => ['key' => 'visit:'.$visit->id, 'name' => $visit->full_name, 'phone' => $visit->visitor_phone, 'source' => 'Kunjungan siswa'])->concat($applicants->map(fn ($applicant) => ['key' => 'applicant:'.$applicant->id, 'name' => $applicant->biodata?->full_name ?? $applicant->user?->name, 'phone' => $applicant->user?->phone, 'source' => 'Pendaftar']))->unique(fn ($candidate) => preg_replace('/\D+/', '', (string) $candidate['phone']))->values()), formAmount: @js($formFeeAmount) })">
            <button type="button" @click="inputOpen=true" class="rounded-xl bg-violet-700 px-5 py-3 text-sm font-black text-white shadow-sm transition hover:bg-violet-800">+ Catat pembayaran</button>
            <template x-teleport="body"><div x-cloak x-show="inputOpen" x-transition.opacity class="fixed inset-0 z-[200] flex items-center justify-center bg-slate-950/55 p-4" @keydown.escape.window="inputOpen=false"><section @click.outside="inputOpen=false" class="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-3xl border border-violet-100 bg-white shadow-2xl">
            <div class="flex items-center justify-between border-b border-violet-100 bg-violet-50/70 px-5 py-4 sm:px-6"><div><p class="text-[11px] font-black uppercase tracking-[.16em] text-violet-700">Pembayaran masuk</p><h2 class="mt-0.5 text-xl font-black text-slate-950">Catat pembayaran</h2></div><button type="button" @click="inputOpen=false" class="rounded-xl px-3 py-2 text-sm font-black text-slate-500 transition hover:bg-white hover:text-violet-700">Tutup</button></div>
            <form method="POST" action="{{ route(request()->routeIs('admin.*') ? 'admin.pembayaran.store' : 'panitia.pembayaran.store') }}" enctype="multipart/form-data" class="space-y-5 p-5 sm:p-6">@csrf
                <div class="relative" @click.outside="candidateOpen=false"><label class="admin-label">Siswa</label><input type="hidden" name="candidate" :value="selectedKey"><button type="button" @click="candidateOpen=!candidateOpen" class="mt-1 flex w-full items-center justify-between rounded-2xl border-2 border-violet-200 bg-white px-4 py-3 text-left text-sm font-bold text-slate-800 transition hover:border-violet-400 focus:outline-none focus:ring-4 focus:ring-violet-100"><span x-text="selected ? `${selected.name} · ${selected.phone}` : 'Pilih siswa'" :class="selected ? 'text-slate-900' : 'text-slate-500'"></span><svg class="h-5 w-5 text-violet-600 transition-transform" :class="candidateOpen ? 'rotate-180' : ''" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="m6 9 6 6 6-6"/></svg></button><div x-cloak x-show="candidateOpen" x-transition class="absolute left-0 top-full z-[220] mt-2 max-h-60 w-full overflow-y-auto rounded-2xl border border-violet-100 bg-white p-1.5 shadow-2xl"><template x-for="candidate in candidates" :key="candidate.key"><button type="button" @click="selectedKey=candidate.key; candidateOpen=false" class="flex w-full items-center justify-between gap-3 rounded-xl px-3 py-3 text-left hover:bg-violet-50"><span><strong class="block text-sm text-slate-800" x-text="candidate.name"></strong><small class="mt-0.5 block text-xs font-semibold text-slate-500" x-text="candidate.phone"></small></span><span class="rounded-full bg-violet-50 px-2 py-1 text-[10px] font-black text-violet-700" x-text="candidate.source"></span></button></template><p x-show="candidates.length === 0" class="px-3 py-4 text-sm font-semibold text-slate-500">Belum ada data kunjungan atau pendaftar.</p></div></div>
                <div x-cloak x-show="selected" class="flex items-center gap-3 rounded-2xl bg-violet-50 px-4 py-3 text-sm"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-600 font-black text-white">✓</span><div><strong class="block text-slate-800" x-text="selected?.name"></strong><span class="text-xs font-semibold text-slate-500" x-text="selected?.phone"></span></div></div>
                <div><label class="admin-label">Jenis pembayaran</label><input type="hidden" name="fee_type" :value="feeType"><div class="mt-1 grid grid-cols-2 gap-2 rounded-2xl bg-violet-50 p-1.5"><button type="button" @click="feeType='formulir'" class="rounded-xl px-3 py-3 text-sm font-black transition" :class="feeType === 'formulir' ? 'bg-violet-700 text-white shadow-sm' : 'text-violet-800 hover:bg-white'">Formulir</button><button type="button" @click="feeType='daftar_ulang'" class="rounded-xl px-3 py-3 text-sm font-black transition" :class="feeType === 'daftar_ulang' ? 'bg-violet-700 text-white shadow-sm' : 'text-violet-800 hover:bg-white'">Daftar ulang</button></div></div>
                <div class="grid gap-4 sm:grid-cols-2"><div><label class="admin-label" x-text="feeType === 'formulir' ? 'Nominal formulir' : 'Nominal DU'"></label><input type="number" name="amount" min="1" :value="feeType === 'formulir' ? formAmount : '{{ old('amount') }}'" :readonly="feeType === 'formulir'" :required="feeType === 'daftar_ulang'" class="admin-input mt-1" :class="feeType === 'formulir' && 'bg-slate-50 text-slate-500'" :placeholder="feeType === 'formulir' ? '' : 'Nominal diterima'"><p x-show="feeType === 'formulir'" class="mt-1 text-xs font-semibold text-violet-700">Sudah ditetapkan keuangan.</p><p x-show="feeType === 'daftar_ulang'" class="mt-1 text-xs font-semibold text-slate-500">DU boleh dicicil.</p></div><div><label class="admin-label">Metode</label><input type="hidden" name="payment_method" :value="paymentMethod"><div class="mt-1 grid grid-cols-2 gap-2 rounded-2xl bg-violet-50 p-1.5"><button type="button" @click="paymentMethod='cash'" class="rounded-xl px-3 py-3 text-sm font-black transition" :class="paymentMethod === 'cash' ? 'bg-violet-700 text-white shadow-sm' : 'text-violet-800 hover:bg-white'">Tunai</button><button type="button" @click="paymentMethod='transfer'" class="rounded-xl px-3 py-3 text-sm font-black transition" :class="paymentMethod === 'transfer' ? 'bg-violet-700 text-white shadow-sm' : 'text-violet-800 hover:bg-white'">Transfer</button></div></div></div>
                <div class="grid gap-4 sm:grid-cols-2"><div><label class="admin-label">Bukti pembayaran</label><input type="file" name="proof_file" accept=".jpg,.jpeg,.png,.pdf" required class="admin-input mt-1"><p class="mt-1 text-xs font-medium text-slate-500">JPG, PNG, atau PDF · maks. 2 MB</p></div><div><label class="admin-label">Catatan <span class="font-medium text-slate-400">(opsional)</span></label><input name="reference_number" value="{{ old('reference_number') }}" class="admin-input mt-1" placeholder="Contoh: nomor transfer"></div></div>
                <button class="w-full rounded-xl bg-violet-700 px-5 py-3.5 text-sm font-black text-white shadow-sm transition hover:bg-violet-800">Simpan & setujui pembayaran</button>
            </form>
            </section></div></template>
        </div>
        @else
        <section class="mb-6 rounded-3xl border border-violet-100 bg-white p-5 shadow-sm"><p class="text-xs font-black uppercase tracking-[.14em] text-violet-700">Persetujuan pembayaran</p><h2 class="mt-1 text-xl font-black text-slate-950">Periksa dan setujui bukti pembayaran</h2><p class="mt-1 text-sm text-slate-500">Kepala sekolah dapat menyetujui atau menolak pembayaran yang masuk. Pencatatan pembayaran dilakukan oleh panitia.</p></section>
        @endif
        <x-payment-transaction-table :transactions="$transactions" :route-prefix="request()->routeIs('admin.*') ? 'admin.' : 'panitia.'" accent="violet" show-pagination />
    </div>
    <script>
        function paymentEntry(config) {
            return {
                candidates: config.candidates || [], formAmount: config.formAmount || 0, inputOpen: {{ $errors->any() ? 'true' : 'false' }}, candidateOpen: false, selectedKey: @js(old('candidate', '')), feeType: @js(old('fee_type', 'formulir')), paymentMethod: @js(old('payment_method', 'cash')),
                get selected() { return this.candidates.find((candidate) => candidate.key === this.selectedKey) || null; },
            };
        }
    </script>
@endsection
