@extends('layouts.app', ['title' => 'Pembayaran'])
@section('content')
<div class="card"><h1 style="margin-top:0">Pembayaran SPMB</h1><p class="muted">Alur: bukti bayar → persetujuan panitia → penerimaan bendahara. Formulir dapat diisi setelah disetujui panitia.</p></div>
<div class="card"><h2>Catat pembayaran</h2><form method="post" action="{{ route('payments.store') }}" enctype="multipart/form-data" class="grid">@csrf
@if(auth()->user()->role !== 'siswa')<label>Siswa terdaftar <select name="siswa_id"><option value="">— Buat calon siswa & akun otomatis —</option>@foreach($siswas as $s)<option value="{{ $s->id }}">{{ $s->nama }} · {{ $s->phone }}</option>@endforeach</select></label><label>Nama calon siswa <input name="nama_siswa" value="{{ old('nama_siswa') }}" placeholder="Wajib jika siswa baru"></label><label>WhatsApp calon siswa <input name="phone_siswa" value="{{ old('phone_siswa') }}" placeholder="08xxxxxxxxxx"></label><label>Email calon siswa <input name="email_siswa" value="{{ old('email_siswa') }}"></label>@endif
<label>Jenis pembayaran <select name="payment_type" id="payment-type"><option value="formulir">Formulir</option><option value="du">Daftar ulang (DU) — sekali</option></select></label><label>Metode <select name="method"><option value="transfer">Transfer</option><option value="cash">Tunai</option></select></label><label>Rekening tujuan <select name="bank_account_id"><option value="">Pilih rekening (wajib transfer)</option>@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->bank_name }} · {{ $a->account_number }} a/n {{ $a->account_holder }}</option>@endforeach</select></label><label>Nominal (Rp)<input type="number" min="1" name="amount" value="{{ old('amount') }}" required></label><label>Tanggal bayar<input type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\\TH:i') }}" required></label><label>Bukti pembayaran (JPG, PNG, atau PDF)<input type="file" name="proof" accept="image/jpeg,image/png,application/pdf" required></label><label class="wide">Catatan <textarea name="notes">{{ old('notes') }}</textarea></label><div class="wide"><button>Simpan dan kirim ke panitia</button></div></form></div>
<div class="card"><h2>Riwayat pembayaran</h2><table><thead><tr><th>Invoice / Siswa</th><th>Jenis</th><th>Nominal</th><th>Status</th><th>Persetujuan</th><th>Aksi</th></tr></thead><tbody>@forelse($payments as $p)<tr><td><b>{{ $p->invoice_number }}</b><br>{{ $p->siswa->nama }}<br><small>{{ $p->method }} · bukti: <a href="{{ asset('storage/'.$p->proof_path) }}" target="_blank">lihat</a></small></td><td>{{ strtoupper($p->payment_type) }}</td><td>Rp {{ number_format($p->amount,0,',','.') }}</td><td><span class="badge">{{ str_replace('_',' ', $p->status) }}</span></td><td>Panitia: {{ $p->approver?->name ?? '—' }}<br>Bendahara: {{ $p->treasurer?->name ?? '—' }}</td><td>@if($p->status === 'pending_panitia' && in_array(auth()->user()->role,['panitia','admin']))<form method="post" action="{{ route('payments.approve',$p) }}">@csrf<button>Setujui panitia</button></form>@endif @if($p->status === 'approved_panitia' && in_array(auth()->user()->role,['bendahara','admin']))<form method="post" action="{{ route('payments.receive',$p) }}">@csrf @if($p->payment_type === 'du')<details><summary>Pilih rincian DU</summary><div class="checks">@foreach($duFees as $fee=>$amount)<label><input type="checkbox" name="fee_items[]" value="{{ $fee }}">{{ $fee }} — Rp {{ number_format($amount,0,',','.') }}</label>@endforeach</div></details>@endif<button class="warning">Terima bendahara</button></form>@endif @if($p->status === 'received_bendahara')<a class="button secondary" href="{{ route('payments.invoice',$p) }}" target="_blank">Cetak invoice BMT</a>@endif</td></tr>@empty<tr><td colspan="6" class="muted">Belum ada pembayaran.</td></tr>@endforelse</tbody></table></div>
<div class="card"><b>Informasi DU</b><p class="muted">DU SPMB hanya dibayar satu kali. Pembayaran berikutnya dilakukan melalui BMT PCM Cileungsi setiap Selasa dan Jumat, pukul 07.30–14.30 WIB, di Kampus E SMK Muhammadiyah 4 Cileungsi. Biaya formulir tidak termasuk rincian biaya DU.</p></div>
@endsection
