@php
    use Illuminate\Support\Str;
    $schoolName = $siteSettings['school_name'] ?? 'SMK Muhammadiyah 4 Cileungsi';
    $shortName = $siteSettings['school_short_name'] ?? $schoolName;
    $heroTitle = $siteSettings['tagline'] ?? 'Bekerja & Kuliah';
    $heroDescription = $siteSettings['hero_description'] ?? 'Sekolah vokasi yang menyiapkan siswa untuk bekerja, kuliah, dan berwirausaha.';
    $programImages = [
        'Kuliner' => 'images/konsentrasi/kuliner/plating-hidangan.png',
        'Desain dan Produksi Busana' => 'images/konsentrasi/busana/praktik-menjahit.png',
        'Layanan Kefarmasian Klinis dan Komunitas' => 'images/konsentrasi/farmasi/pelayanan-kefarmasian.png',
        'Layanan Penunjang Keperawatan dan Caregiving' => 'images/konsentrasi/keperawatan/praktik-perawatan-dasar.png',
    ];
@endphp
<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $schoolName }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap" rel="stylesheet">
    <style>
        :root{--navy:#092e6a;--blue:#1768d1;--sky:#e9f6ff;--yellow:#ffd248;--ink:#102a53;--muted:#6881a5;--line:#d9e8f7}*{box-sizing:border-box}body{margin:0;background:#fbfdff;color:var(--ink);font-family:'DM Sans',sans-serif}.shell{width:min(1160px,calc(100% - 40px));margin:auto}.top{position:fixed;z-index:20;inset:22px 0 auto}.nav{height:74px;padding:0 20px;display:flex;align-items:center;gap:25px;background:#ffffffed;backdrop-filter:blur(14px);border:1px solid #fff;border-radius:22px;box-shadow:0 14px 36px #092e6a1a;animation:enter .7s both}.identity{display:flex;gap:11px;align-items:center;text-decoration:none;color:var(--navy);font:800 13px/1.05 'Plus Jakarta Sans'}.mark{display:grid;place-items:center;width:42px;height:42px;border-radius:14px;background:var(--navy);color:#fff;font-size:17px}.identity small{font:700 9px 'DM Sans';letter-spacing:.13em;color:#4b75b0}.navlinks{display:flex;gap:18px;margin-left:auto}.navlinks a{font-size:12px;font-weight:700;color:#28476f;text-decoration:none}.navlinks a:first-child{color:var(--blue)}.nav-action{padding:11px 16px;border-radius:12px;background:var(--navy);font:700 12px 'Plus Jakarta Sans';color:#fff;text-decoration:none}.hamb{display:none;border:0;background:#e8f3ff;border-radius:12px;width:40px;height:40px;color:var(--navy)}
        .hero{min-height:680px;position:relative;overflow:hidden;padding:128px 0 68px;background:linear-gradient(125deg,#effaff,#dcefff 53%,#c0dfff)}.hero:before{content:'';position:absolute;width:570px;height:570px;right:-100px;top:-155px;border-radius:50%;background:#fff6}.hero:after{content:'';position:absolute;width:260px;height:260px;left:-110px;bottom:-140px;border-radius:50%;border:44px solid #c8e8ff}.hero-grid{position:relative;z-index:1;display:grid;grid-template-columns:1fr .95fr;gap:35px}.hero-copy{animation:slide .9s .15s both}.hero h1{max-width:650px;margin:76px 0 0;color:var(--navy);font:800 clamp(43px,5.1vw,66px)/.98 'Plus Jakarta Sans';letter-spacing:-.065em}.hero h1 span{color:var(--blue)}.hero-note{max-width:570px;margin:18px 0;color:#42658f;font-size:15px;line-height:1.65}.actions{display:flex;gap:12px;margin-top:26px}.button{padding:14px 19px;border-radius:14px;text-decoration:none;font:700 13px 'Plus Jakarta Sans';transition:.3s}.button:hover{transform:translateY(-4px);box-shadow:0 16px 28px #0d3d7d30}.primary{background:var(--navy);color:#fff;box-shadow:0 13px 25px #0d3d7d38}.ghost{background:#fff;color:var(--navy);border:1px solid #d4e5f8}.art{position:relative;height:410px;animation:slide-r 1s .3s both}.orbit{position:absolute;width:350px;height:350px;left:50%;top:0;transform:translateX(-50%);border-radius:50%;background:var(--yellow);box-shadow:inset 0 0 0 18px #ffe992;animation:breathe 6s infinite}.showcase{position:absolute;bottom:0;left:10%;right:2%;height:335px;padding:21px;border-radius:32px 32px 23px;background:linear-gradient(145deg,#1262bf,#0b438f);box-shadow:0 28px 44px #0a4d9633;animation:float 5.5s ease-in-out infinite}.showcase:before{content:'SMK';position:absolute;inset:20px;border:1px solid #ffffff55;border-radius:22px;color:#ffffff18;text-align:right;padding:18px;font:800 92px 'Plus Jakarta Sans'}.visual-lines{position:absolute;left:42px;right:42px;bottom:47px;display:grid;gap:11px}.visual-lines span{height:14px;border-radius:50px;background:#ffffffdb}.visual-lines span:nth-child(2){width:72%;background:#ffffff88}.visual-lines span:nth-child(3){width:42%;background:#ffffff55}
        .shortcuts{position:relative;z-index:2;margin-top:-40px}.shortcuts-grid{display:grid;grid-template-columns:repeat(4,1fr);padding:9px;border-radius:22px;background:#fff;box-shadow:0 18px 35px #0b47881a}.shortcut{display:flex;align-items:center;gap:12px;padding:16px;border-right:1px solid var(--line);text-decoration:none;color:var(--ink);font:700 12px 'Plus Jakarta Sans';transition:.35s}.shortcut:hover{background:#f4faff;transform:translateY(-4px)}.shortcut:last-child{border-right:0}.shortcut b{display:grid;place-items:center;width:37px;height:37px;border-radius:12px;background:#e6f3ff;color:var(--blue);font-size:15px}.shortcut:nth-child(even) b{background:#fff5ca;color:#c88b00}
        section{padding:92px 0}.label{font-size:10px;font-weight:700;letter-spacing:.17em;text-transform:uppercase;color:#2970c5}.heading{margin:8px 0;color:var(--navy);font:800 38px/1.1 'Plus Jakarta Sans';letter-spacing:-.05em}.subhead{max-width:500px;margin:13px 0;color:var(--muted);line-height:1.7;font-size:14px}.section-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:30px}.more{font:700 12px 'Plus Jakarta Sans';color:var(--blue);text-decoration:none}.feature-grid{display:grid;grid-template-columns:1.2fr .8fr .8fr;gap:18px}.feature{min-height:280px;position:relative;overflow:hidden;padding:23px;border-radius:24px;background:#e9f5ff;transition:.4s}.feature:hover,.program:hover{transform:translateY(-9px);box-shadow:0 22px 36px #0d4c8d22}.feature.large{background:var(--navy);color:#fff}.feature.large:after{content:'01';position:absolute;right:-15px;bottom:-58px;color:#ffffff12;font:800 210px 'Plus Jakarta Sans'}.feature-icon{display:grid;place-items:center;width:45px;height:45px;border-radius:15px;background:#fff;color:var(--blue);font-size:19px}.feature h3{position:relative;z-index:1;margin:75px 0 8px;font:700 20px/1.25 'Plus Jakarta Sans'}.feature p{position:relative;z-index:1;margin:0;color:#c9def9;line-height:1.65;font-size:13px}.feature:not(.large) h3{margin-top:75px;color:var(--navy)}.feature:not(.large) p{color:var(--muted)}.program-zone{background:#f0f8ff}.program-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-top:30px}.program{padding:24px;border-radius:22px;background:#fff;box-shadow:0 11px 27px #0c4b8c0e;transition:.4s}.program-num{color:#bad5f3;font:800 36px/1 'Plus Jakarta Sans'}.program h3{margin:39px 0 9px;font:700 17px 'Plus Jakarta Sans'}.program p{margin:0;color:var(--muted);font-size:13px;line-height:1.65}.program a{display:inline-block;margin-top:22px;color:var(--blue);font-size:12px;font-weight:700;text-decoration:none}.banner{overflow:hidden;position:relative;padding:65px;border-radius:30px;background:var(--navy);color:#fff}.banner:after{content:'✦';position:absolute;right:7%;top:-65px;color:#ffffff10;font-size:300px}.banner>*{position:relative;z-index:1}.banner .heading{max-width:600px;color:#fff}.banner p{max-width:550px;line-height:1.7;color:#cbddf5}.footer{padding:50px 0 24px;background:#061e47;color:#a9c8ed}.footer-grid{display:grid;grid-template-columns:1.8fr 1fr 1fr;gap:40px}.footer .identity{color:#fff}.footer p,.footer a{font-size:12px;line-height:1.7;color:#a9c8ed;text-decoration:none}.footer h4{margin:6px 0 15px;color:#fff;font:700 13px 'Plus Jakarta Sans'}.footer a{display:block;margin:8px 0}.copy{margin-top:35px;padding-top:18px;border-top:1px solid #ffffff18;font-size:10px}
        .reveal{opacity:0;transform:translateY(34px);transition:.8s}.reveal.is-visible{opacity:1;transform:none}.reveal .feature,.reveal .program,.reveal .banner{opacity:0;transform:translateY(22px);transition:.7s}.reveal.is-visible .feature,.reveal.is-visible .program,.reveal.is-visible .banner{opacity:1;transform:none}.reveal.is-visible .feature:nth-child(2),.reveal.is-visible .program:nth-child(2){transition-delay:.12s}.reveal.is-visible .feature:nth-child(3),.reveal.is-visible .program:nth-child(3){transition-delay:.24s}.reveal.is-visible .feature:nth-child(4),.reveal.is-visible .program:nth-child(4){transition-delay:.36s}@keyframes enter{from{opacity:0;transform:translateY(-18px)}to{opacity:1;transform:none}}@keyframes slide{from{opacity:0;transform:translateX(-30px)}to{opacity:1;transform:none}}@keyframes slide-r{from{opacity:0;transform:translateX(35px)}to{opacity:1;transform:none}}@keyframes breathe{50%{transform:translateX(-50%) scale(1.055)}}@keyframes float{50%{transform:translateY(-12px)}}@media(max-width:780px){.navlinks,.nav-action{display:none}.hamb{display:block;margin-left:auto}.hero{min-height:auto;padding:96px 0 38px}.hero-grid{grid-template-columns:1fr}.hero-copy{text-align:center}.hero h1{margin-top:35px}.hero-note{margin-inline:auto}.actions{justify-content:center}.art{height:285px;margin-top:8px;transform:scale(.9)}.showcase{height:270px}.orbit{width:295px;height:295px}.shortcuts{margin-top:-20px}.shortcuts-grid{grid-template-columns:1fr 1fr}.shortcut{border-bottom:1px solid var(--line)}.shortcut:nth-child(2){border-right:0}.feature-grid{grid-template-columns:1fr}.feature{min-height:220px}.program-grid{grid-template-columns:1fr 1fr}.section-head{display:block}.more{display:inline-block;margin-top:15px}.footer-grid{grid-template-columns:1fr 1fr}.footer-grid>div:first-child{grid-column:span 2}}@media(max-width:480px){.shell{width:min(100% - 28px,1160px)}.top{top:12px}.nav{height:62px;border-radius:18px;padding:0 14px}.mark{width:37px;height:37px}.hero h1{font-size:42px}.hero-note{font-size:14px}.art{margin-inline:-26px}.program-grid{grid-template-columns:1fr}.heading{font-size:32px}.shortcut{padding:13px 9px;font-size:10px;gap:7px}.shortcut b{width:31px;height:31px}.banner{padding:35px 25px}.footer-grid{grid-template-columns:1fr}.footer-grid>div:first-child{grid-column:auto}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;transition-duration:.01ms!important}}
    </style>
    <style>.top .identity>span:not(.mark),.footer .identity>span:not(.mark){font-size:0!important}.top .identity>span:not(.mark):before,.footer .identity>span:not(.mark):before{display:block;content:'SMK Muhammadiyah 4 Cileungsi';font:800 13px/1.05 'Plus Jakarta Sans';color:inherit}.top .identity small,.footer .identity small{display:block;font-size:0!important}.top .identity small:after,.footer .identity small:after{content:'Cerdas Rohani, Tangguh Kompetensi, Lestari Aksi.';font:700 8px/1.35 'DM Sans';letter-spacing:.03em;color:#4b75b0}.footer .identity small:after{color:#7fa4d7}.shortcuts+section .section-head .subhead{display:none}.footer{padding:44px 0 20px}.footer .footer-grid{grid-template-columns:1.45fr .72fr .9fr;gap:64px}.footer .identity{display:flex!important;align-items:center;margin:0!important}.footer .identity .mark{flex:0 0 auto}.footer .identity>span:not(.mark){display:block}.footer .identity small{margin-top:5px}.footer .footer-grid>div:first-child>p{max-width:440px;margin:18px 0 0}.footer h4{margin:0 0 14px}.footer a{margin:0 0 10px}@media(max-width:800px){.footer{padding:38px 0 20px}.footer .footer-grid{grid-template-columns:1fr;gap:32px}.footer .footer-grid>div:first-child>p{margin-top:15px}.footer h4{margin-bottom:12px}.footer a{margin-bottom:9px}}</style>
    <style>
        .top{position:fixed;top:0;right:0;left:0;z-index:40;padding:14px 20px;background:#f7fbffcc;backdrop-filter:blur(14px)}
        main{padding-top:98px}
        .nav{height:70px}
        .hero{min-height:auto;padding:60px 0 70px}
        .hero h1{margin-top:0}
        @media(min-width:801px){.hero-grid{grid-template-columns:1fr .95fr;gap:52px}.art{height:360px}}
        @media(max-width:780px){.top{padding:10px 14px}.nav{height:60px}main{padding-top:80px}.hero{padding-top:40px}}
    </style>
<style>
    .logo-mark{background:#fff;border:1px solid #dce9f8;padding:3px}.logo-mark img{width:100%;height:100%;object-fit:contain}.showcase{padding:0;overflow:hidden;background:#fff}.showcase:before{content:'';z-index:1;background:linear-gradient(105deg,#092e6a40,#092e6a08)}.showcase img{width:100%;height:100%;object-fit:cover;object-position:72% center}.showcase .visual-lines{display:none}.news-card{padding:0;display:flex;min-height:300px;flex-direction:column}.news-card img{height:142px;width:100%;object-fit:cover}.news-card .news-body{padding:20px 22px 22px}.news-card .news-date{display:block;margin-bottom:9px;color:#1768d1;font-family:'DM Sans',sans-serif;font-size:10px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.news-card h3{margin:0 0 8px;font-size:17px}.news-card p{color:var(--muted)}.news-card.large{background:#fff;color:var(--ink)}.news-card.large:after{display:none}.news-card.large h3{color:var(--navy)}.news-card .feature-icon{position:absolute;z-index:2;top:116px;left:20px}.news-card .more{position:relative;z-index:1;display:inline-block;margin-top:15px}
    .nav-group{position:relative}.nav-trigger{display:flex;align-items:center;gap:6px;padding:0;border:0;background:transparent;color:#28476f;font:700 12px 'DM Sans';cursor:pointer}.nav-trigger svg{width:14px;transition:transform .2s}.nav-group.is-open .nav-trigger svg{transform:rotate(180deg)}.subnav{position:absolute;top:calc(100% + 14px);left:-15px;min-width:210px;padding:8px;border-radius:16px;background:#fffffffa;box-shadow:0 18px 38px #092e6a20;opacity:0;visibility:hidden;transform:translateY(-8px);transition:.22s}.nav-group.is-open .subnav{opacity:1;visibility:visible;transform:none}.subnav a{display:block;padding:10px 12px;border-radius:10px!important;color:var(--ink)!important}.subnav a:hover{background:#eef7ff;color:var(--blue)!important}.mobile-menu{display:none}@media(max-width:780px){.hamb{display:grid;place-items:center;padding:0;position:relative}.hamb span,.hamb:before,.hamb:after{content:'';position:absolute;width:17px;height:2px;border-radius:4px;background:currentColor;transition:transform .28s ease,opacity .2s ease}.hamb:before{transform:translateY(-6px)}.hamb:after{transform:translateY(6px)}.hamb.is-open span{opacity:0}.hamb.is-open:before{transform:rotate(45deg)}.hamb.is-open:after{transform:rotate(-45deg)}.mobile-menu{display:block;position:absolute;left:0;right:0;top:calc(100% + 10px);padding:10px;border-radius:20px;background:#fffffffa;box-shadow:0 18px 38px #092e6a24;opacity:0;visibility:hidden;transform:translateY(-12px) scale(.98);transform-origin:top right;transition:opacity .25s ease,transform .25s cubic-bezier(.16,1,.3,1),visibility .25s}.mobile-menu.is-open{opacity:1;visibility:visible;transform:none}.mobile-menu a,.mobile-group-toggle{display:flex;align-items:center;width:100%;padding:13px 14px;border:0;border-radius:12px;background:transparent;color:var(--navy);font:700 13px 'Plus Jakarta Sans';text-align:left;text-decoration:none}.mobile-menu a:hover,.mobile-group-toggle:hover{background:#eef7ff}.mobile-group-toggle{justify-content:space-between;cursor:pointer}.mobile-group-toggle svg{width:18px;transition:transform .25s ease}.mobile-group-toggle.is-open svg{transform:rotate(180deg)}.mobile-subnav{display:grid;grid-template-rows:0fr;transition:grid-template-rows .28s ease}.mobile-subnav.is-open{grid-template-rows:1fr}.mobile-subnav>div{overflow:hidden}.mobile-subnav a{margin-left:12px;padding-block:10px;color:#48688f;font-size:12px}.mobile-menu>a:last-child{margin-top:8px;background:var(--navy);color:#fff}.news-card{min-height:0}.news-card img{height:190px}.news-card .feature-icon{top:164px}}
</style>
<style>
    .news-all{display:inline-flex;align-items:center;padding:11px 15px;border:1px solid #1768d1;border-radius:12px;color:#1768d1;font:700 12px 'Plus Jakarta Sans';text-decoration:none;transition:.25s}.news-all:hover{background:#1768d1;color:#fff}.news-read{display:inline-flex;margin-top:17px;padding:10px 13px;border-radius:11px;background:#e7f3ff;color:#0d55aa;font:700 12px 'Plus Jakarta Sans';text-decoration:none;transition:.25s}.news-read:hover{background:#092e6a;color:#fff}
    /* All news headlines begin directly after the date, including cards 02 and 03. */
    .news-card:not(.large) h3{margin-top:0}
    .program{overflow:hidden;padding:0}
    .program-media{position:relative;height:148px;overflow:hidden;background:#dceeff}
    .program-media:after{position:absolute;inset:0;background:linear-gradient(180deg,transparent 46%,#092e6a55);content:''}
    .program-media img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .55s cubic-bezier(.16,1,.3,1)}
    .program:hover .program-media img{transform:scale(1.08)}
    .program-content{padding:20px 22px 23px}
    .program-num{color:#79afe6;font:800 13px/1 'Plus Jakarta Sans';letter-spacing:.08em}
    .program h3{margin:16px 0 9px}
    .program a{margin-top:19px}
    @media(max-width:780px){.program-media{height:170px}}
    .showcase{height:auto;aspect-ratio:16/9}
    .showcase .hero-montage{display:block;width:100%;height:100%;background:#0b438f;object-fit:contain;object-position:center}
    @media(max-width:780px){.showcase{height:auto}.art{top:-24px;left:-18px}}
</style>
</head>
<style>
    .top .identity small:after,.footer .identity small:after{font-size:10px!important;line-height:1.3!important}
    @media(max-width:780px){.top .identity small:after,.footer .identity small:after{font-size:9px!important}}
</style>
<style>
    .top{padding:16px 20px;background:#f7fbffe8;border-bottom:1px solid #dbeaf8}
    .nav{height:78px;padding:0 20px;gap:26px;border-color:#dbeaf8;border-radius:24px;box-shadow:0 16px 42px #092e6a14}
    .identity{gap:12px}.mark{width:46px;height:46px;border-radius:15px;box-shadow:0 6px 14px #0a3e7b10}
    .top .identity>span:not(.mark):before{font-size:15px!important;letter-spacing:-.025em}
    .top .identity small:after{content:'Cerdas Rohani · Tangguh Kompetensi · Lestari Aksi'!important;margin-top:5px;font-size:9px!important;letter-spacing:.01em!important;white-space:nowrap}
    .navlinks{gap:5px}.navlinks>a,.nav-trigger{padding:10px 12px!important;border-radius:11px}.navlinks>a:hover,.nav-trigger:hover{background:#eef6ff;color:#1268cc!important}.nav-staff-login{padding:11px 13px;border:1px solid #b9d4f5;border-radius:14px;color:#0a4d9d;text-decoration:none;font:700 11px 'Plus Jakarta Sans';white-space:nowrap}.nav-staff-login:hover{background:#eef6ff;border-color:#83b7eb}.nav-action{padding:13px 18px;border-radius:14px;box-shadow:0 10px 20px #092e6a24}
    @media(max-width:780px){.top{padding:12px 14px}.nav{height:66px;padding:0 12px;border-radius:21px}.identity{gap:10px;min-width:0}.mark{width:40px;height:40px;border-radius:13px}.top .identity>span:not(.mark):before{font-size:14px!important}.top .identity small:after{margin-top:4px;font-size:8px!important;letter-spacing:0!important}.nav-staff-login{display:none}.hamb{width:44px;height:44px;border-radius:14px;box-shadow:inset 0 0 0 1px #dceafa}}
</style>
<style>
    .footer .footer-grid>div:first-child>p{display:none}
    .top .identity .mark{flex:0 0 auto}
    .top .identity>span:not(.mark){min-width:0}
    @media(max-width:780px){
        .top .nav{width:100%}
        .top .identity .mark{width:40px;height:40px;flex-basis:40px}
        .top .identity small:after{display:block;max-width:185px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
    }
</style>
<body>
<header class="top"><nav class="nav shell"><a class="identity" href="{{ route('home') }}"><span class="mark logo-mark"><img src="{{ asset('images/logo-sekolah.png') }}" alt="Logo {{ $schoolName }}"></span><span>{{ $shortName }}<br><small>SEKOLAH VOKASI</small></span></a><div class="navlinks"><a href="{{ route('home') }}">Beranda</a><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false">Tentang <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m6 9 6 6 6-6"/></svg></button><div class="subnav"><a href="{{ route('profil') }}">Profil Sekolah</a><a href="{{ route('tentang.page', 'sejarah') }}">Sejarah Sekolah</a><a href="{{ route('tentang.page', 'pimpinan') }}">Pimpinan Sekolah</a></div></div><div class="nav-group"><button class="nav-trigger" type="button" aria-expanded="false">Pendidikan <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m6 9 6 6 6-6"/></svg></button><div class="subnav"><a href="{{ route('jurusan') }}">Konsentrasi Keahlian</a><a href="{{ route('pendidikan.page', 'program-studi') }}">Program Sekolah</a><a href="{{ route('pendidikan.page', 'fasilitas') }}">Fasilitas</a></div></div><a href="{{ route('pengumuman') }}">Informasi</a><a href="{{ route('kontak') }}">Kontak</a></div><a href="{{ route('register') }}" class="nav-action">Daftar SPMB</a><button class="hamb" type="button" aria-label="Buka menu" aria-expanded="false" aria-controls="mobile-menu"><span></span></button><div class="mobile-menu" id="mobile-menu"><a href="{{ route('home') }}">Beranda</a><button class="mobile-group-toggle" type="button" aria-expanded="false">Tentang <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m6 9 6 6 6-6"/></svg></button><div class="mobile-subnav"><div><a href="{{ route('profil') }}">Profil Sekolah</a><a href="{{ route('tentang.page', 'sejarah') }}">Sejarah Sekolah</a><a href="{{ route('tentang.page', 'pimpinan') }}">Pimpinan Sekolah</a></div></div><button class="mobile-group-toggle" type="button" aria-expanded="false">Pendidikan <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m6 9 6 6 6-6"/></svg></button><div class="mobile-subnav"><div><a href="{{ route('jurusan') }}">Konsentrasi Keahlian</a><a href="{{ route('pendidikan.page', 'program-studi') }}">Program Sekolah</a><a href="{{ route('pendidikan.page', 'fasilitas') }}">Fasilitas</a></div></div><a href="{{ route('pengumuman') }}">Informasi</a><a href="{{ route('kontak') }}">Kontak</a><a href="{{ route('register') }}">Daftar SPMB</a></div></nav></header>
<main>
<section class="hero"><div class="shell hero-grid"><div class="hero-copy"><h1>SMK Muhammadiyah 4 <span>Cileungsi.</span></h1><p class="hero-note">SIMUPA — Sivitas Akademika Muhammadiyah 4. Tempat belajar, berkarya, dan siap menghadapi masa depan.</p><div class="actions"><a href="{{ route('jurusan') }}" class="button primary">Jelajahi Konsentrasi</a><a href="{{ route('profil') }}" class="button ghost">Tentang Kami</a></div></div><div class="art"><div class="orbit"></div><div class="showcase"><img class="hero-montage" src="{{ asset('images/landing/hero-konsentrasi-montage-v1.png') }}" alt="Kegiatan praktik Kuliner, Busana, Farmasi, dan Keperawatan di SMK Muhammadiyah 4 Cileungsi"><div class="visual-lines"><span></span><span></span><span></span></div></div></div></div></section>
<div class="shortcuts"><div class="shell shortcuts-grid"><a class="shortcut" href="{{ route('profil') }}"><b>◈</b>Profil Sekolah</a><a class="shortcut" href="{{ route('jurusan') }}"><b>↗</b>4 Konsentrasi Keahlian</a><a class="shortcut" href="{{ route('alur') }}"><b>◎</b>SPMB SIMUPA</a><a class="shortcut" href="{{ route('pengumuman') }}"><b>✦</b>Informasi Sekolah</a></div></div>
<section class="reveal"><div class="shell"><div class="section-head"><div><span class="label">Sorotan sekolah</span><h2 class="heading">Informasi terbaru</h2><p class="subhead">Artikel dan kabar sekolah yang diterbitkan oleh admin.</p></div><a class="news-all" href="{{ route('pengumuman') }}">Lihat semua informasi</a></div><div class="feature-grid">@forelse($pengumumans as $pengumuman)<article class="feature news-card {{ $loop->first ? 'large' : '' }}"><img src="{{ asset($pengumuman->gallery[0] ?? 'images/landing/'.(['activity-seni.png','activity-pramuka.png','activity-futsal.png'][$loop->index % 3])) }}" alt="{{ $pengumuman->judul }}"><span class="feature-icon">{{ $loop->first ? '✦' : '◌' }}</span><div class="news-body"><span class="news-date">{{ ($pengumuman->tampil_mulai ?: $pengumuman->created_at)?->translatedFormat('d F Y') }}</span><h3>{{ $pengumuman->judul }}</h3><p>{{ Str::limit($pengumuman->isi,100,'...') }}</p><a class="news-read" href="{{ route('pengumuman.artikel',$pengumuman) }}">Selengkapnya</a></div></article>@empty<article class="feature news-card large"><img src="{{ asset('images/landing/activity-seni.png') }}" alt="Kegiatan seni siswa"><span class="feature-icon">✦</span><div class="news-body"><span class="news-date">08 September 2026</span><h3>Festival Seni dan Kreativitas Siswa</h3><p>Siswa menampilkan karya, musik, dan pertunjukan dalam agenda sekolah.</p><a class="news-read" href="{{ route('pengumuman') }}">Selengkapnya</a></div></article><article class="feature news-card"><img src="{{ asset('images/landing/activity-pramuka.png') }}" alt="Kegiatan Pramuka"><span class="feature-icon">◌</span><div class="news-body"><span class="news-date">02 September 2026</span><h3>Latihan Kepemimpinan Pramuka</h3><p>Belajar kerja sama, disiplin, dan tanggung jawab bersama.</p><a class="news-read" href="{{ route('pengumuman') }}">Selengkapnya</a></div></article><article class="feature news-card"><img src="{{ asset('images/landing/activity-futsal.png') }}" alt="Latihan futsal siswa"><span class="feature-icon">↗</span><div class="news-body"><span class="news-date">28 Agustus 2026</span><h3>Ekstrakurikuler Futsal</h3><p>Ruang bagi siswa untuk aktif, sehat, dan berprestasi.</p><a class="news-read" href="{{ route('pengumuman') }}">Selengkapnya</a></div></article>@endforelse</div></div></section>
<section class="program-zone reveal"><div class="shell"><div class="section-head"><div><span class="label">Konsentrasi keahlian</span><h2 class="heading">Pilih fokus untuk masa depanmu</h2><p class="subhead">Pilih konsentrasi yang sesuai dengan minat dan rencana masa depanmu.</p></div><a class="more" href="{{ route('jurusan') }}">Lihat semua konsentrasi →</a></div><div class="program-grid">@forelse($jurusans as $jurusan)<article class="program"><div class="program-media"><img src="{{ asset($programImages[$jurusan->name] ?? 'images/landing/campus-hero-v1.png') }}" alt="Kegiatan {{ $jurusan->name }}"></div><div class="program-content"><span class="program-num">{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><h3>{{ $jurusan->name }}</h3><p>{{ $jurusan->visitorSummary() }}</p><a href="{{ route('konsentrasi.show', $jurusan) }}">Lihat detail →</a></div></article>@empty<article class="program"><div class="program-content"><span class="program-num">01</span><h3>Konsentrasi Keahlian</h3><p>Informasi konsentrasi akan ditampilkan di sini.</p></div></article>@endforelse</div></div></section>
<section class="reveal"><div class="shell"><div class="banner"><span class="label" style="color:#ffd248">PENERIMAAN PESERTA DIDIK BARU</span><h2 class="heading">{{ $gelombangAktif?->name ? $gelombangAktif->name.' sedang dibuka.' : 'Siapkan langkahmu bersama kami.' }}</h2><p>Temukan alur pendaftaran, biaya, jadwal, dan informasi lengkap sebelum mendaftar.</p><a href="{{ route('alur') }}" class="button" style="display:inline-block;margin-top:14px;background:#ffd248;color:#092e6a">Lihat informasi PPDB</a></div></div></section>
</main>
<footer class="footer"><div class="shell"><div class="footer-grid"><div><a class="identity" href="{{ route('home') }}"><span class="mark logo-mark"><img src="{{ asset('images/logo-sekolah.png') }}" alt="Logo {{ $schoolName }}"></span><span>{{ $shortName }}<br><small>SEKOLAH VOKASI</small></span></a><p>{{ $siteSettings['footer_description'] ?? 'Membentuk generasi yang berkarakter, kompeten, dan siap menghadapi masa depan.' }}</p></div><div><h4>Navigasi</h4><a href="{{ route('profil') }}">Profil Sekolah</a><a href="{{ route('jurusan') }}">Konsentrasi Keahlian</a><a href="{{ route('pengumuman') }}">Informasi</a></div><div><h4>Kontak</h4><a href="tel:{{ $siteSettings['contact_phone'] ?? '' }}">{{ $siteSettings['contact_phone'] ?? 'Hubungi sekolah' }}</a><a href="{{ route('kontak') }}">{{ $siteSettings['school_address'] ?? 'Lihat alamat sekolah' }}</a><a href="{{ route('kontak') }}">Kontak lengkap →</a></div></div><div class="copy">© 2026 <a href="https://sompetech.ilhamsompe5.workers.dev" target="_blank" rel="noopener noreferrer" style="display: inline; margin: 0; padding: 0; color: inherit; text-decoration: none; border: 0; outline: none; background: transparent; box-shadow: none;">Ilham Sompe &amp; Team.</a></div></div></footer>
<script>const observer=new IntersectionObserver((entries,obs)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');obs.unobserve(entry.target)}}),{threshold:.16});document.querySelectorAll('.reveal').forEach(section=>observer.observe(section));const desktopGroups=document.querySelectorAll('.nav-group');desktopGroups.forEach(group=>{const button=group.querySelector('.nav-trigger');button.addEventListener('click',event=>{event.stopPropagation();const open=!group.classList.contains('is-open');desktopGroups.forEach(item=>{item.classList.remove('is-open');item.querySelector('.nav-trigger').setAttribute('aria-expanded','false')});group.classList.toggle('is-open',open);button.setAttribute('aria-expanded',String(open))})});const menuButton=document.querySelector('.hamb'),mobileMenu=document.querySelector('.mobile-menu');const closeMobileSubmenus=()=>{mobileMenu.querySelectorAll('.mobile-subnav').forEach(item=>item.classList.remove('is-open'));mobileMenu.querySelectorAll('.mobile-group-toggle').forEach(item=>{item.classList.remove('is-open');item.setAttribute('aria-expanded','false')})};const closeMenu=()=>{menuButton.classList.remove('is-open');mobileMenu.classList.remove('is-open');closeMobileSubmenus();menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Buka menu')};menuButton.addEventListener('click',event=>{event.stopPropagation();const open=!mobileMenu.classList.contains('is-open');mobileMenu.classList.toggle('is-open',open);menuButton.classList.toggle('is-open',open);if(!open)closeMobileSubmenus();menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Tutup menu':'Buka menu')});mobileMenu.querySelectorAll('.mobile-group-toggle').forEach(button=>button.addEventListener('click',()=>{const submenu=button.nextElementSibling;const open=!submenu.classList.contains('is-open');closeMobileSubmenus();submenu.classList.toggle('is-open',open);button.classList.toggle('is-open',open);button.setAttribute('aria-expanded',String(open))}));mobileMenu.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));document.addEventListener('click',event=>{desktopGroups.forEach(item=>{if(!item.contains(event.target)){item.classList.remove('is-open');item.querySelector('.nav-trigger').setAttribute('aria-expanded','false')}});if(!menuButton.closest('.nav').contains(event.target))closeMenu()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&mobileMenu.classList.contains('is-open')){closeMenu();menuButton.focus()}});window.matchMedia('(min-width:781px)').addEventListener('change',event=>{if(event.matches)closeMenu()});</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const url="{{ route('tentang.page','sambutan-kepala-sekolah') }}",label='Sambutan Kepala Sekolah';const desktop=document.querySelector('.subnav'),mobile=document.querySelector('.mobile-subnav div');[desktop,mobile].filter(Boolean).forEach(menu=>{const structure=menu.querySelector('[href*="/pimpinan"]'),featured=menu.parentElement.parentElement.querySelector('[href*="/program-studi"]');if(structure)structure.textContent='Struktur Organisasi';if(featured)featured.textContent='Program Sekolah'});if(desktop&&!desktop.querySelector('[href*="sambutan-kepala-sekolah"]'))desktop.insertAdjacentHTML('beforeend',`<a href="${url}">${label}</a>`);if(mobile&&!mobile.querySelector('[href*="sambutan-kepala-sekolah"]'))mobile.insertAdjacentHTML('beforeend',`<a href="${url}">${label}</a>`)});</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const login='{{ route('login') }}',signup=document.querySelector('.nav-action'),mobile=document.querySelector('.mobile-menu'),mobileSignup=mobile?.querySelector('[href="{{ route('register') }}"]');if(signup&&!document.querySelector('.nav-staff-login'))signup.insertAdjacentHTML('beforebegin',`<a class="nav-staff-login" href="${login}">Masuk Petugas</a>`);if(mobile&&mobileSignup&&!mobile.querySelector(`[href="${login}"]`))mobileSignup.insertAdjacentHTML('beforebegin',`<a href="${login}">Masuk Petugas</a>`)});</script>
</body></html>
