@extends('layouts.school')

@section('title', 'Program unggulan')

@section('content')
<style>
.featured-page{background:#f6fbff;color:#092e6a}.featured-wrap{width:min(1160px,calc(100% - 40px));margin:auto}.featured-hero{position:relative;overflow:hidden;padding:66px 0 74px;background:#092e6a;color:#fff}.featured-hero:after{position:absolute;right:-110px;bottom:-225px;width:530px;height:530px;border:66px solid #2b72be70;border-radius:50%;content:''}.featured-hero-grid{position:relative;z-index:1;display:grid;grid-template-columns:1fr .88fr;align-items:center;gap:58px}.featured-kicker{margin:0;color:#ffd248;font:800 11px 'DM Sans';letter-spacing:.2em}.featured-hero h1{max-width:620px;margin:15px 0;color:#fff;font:800 clamp(42px,5.2vw,68px)/1.02 'Plus Jakarta Sans';letter-spacing:-.06em}.featured-hero p{max-width:545px;margin:0;color:#d1e5ff;font-size:16px;line-height:1.75}.featured-stat{padding:25px;border:1px solid #ffffff30;border-radius:24px;background:#ffffff12;backdrop-filter:blur(8px)}.featured-stat b{display:block;color:#ffd248;font:800 43px/1 'Plus Jakarta Sans'}.featured-stat span{display:block;margin-top:9px;color:#e6f2ff;font-size:14px;line-height:1.5}.featured-body{padding:62px 0 82px}.featured-head{display:flex;align-items:end;justify-content:space-between;gap:30px;margin-bottom:29px}.featured-head small{color:#1768d1;font:800 10px 'DM Sans';letter-spacing:.18em}.featured-head h2{margin:11px 0 0;color:#092e6a;font:800 clamp(31px,3.4vw,46px)/1.08 'Plus Jakarta Sans';letter-spacing:-.05em}.featured-head p{max-width:380px;margin:0;color:#607c9f;font-size:14px;line-height:1.7}.featured-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:17px}.featured-card{position:relative;overflow:hidden;min-height:315px;padding:28px;border:1px solid #d7e9fa;border-radius:25px;background:#fff;box-shadow:0 13px 30px #0b417e10;transition:transform .3s,box-shadow .3s}.featured-card:hover{transform:translateY(-7px);box-shadow:0 24px 38px #0b417e1c}.featured-card:nth-child(2){background:#e9f6ff}.featured-card:nth-child(3){background:#092e6a}.featured-card:nth-child(3) h3,.featured-card:nth-child(3) p{color:#fff}.featured-card:nth-child(3) p{color:#cfe5ff}.featured-icon{display:grid;place-items:center;width:47px;height:47px;border-radius:15px;background:#ffd248;color:#092e6a;font:800 17px 'Plus Jakarta Sans'}.featured-card h3{margin:75px 0 0;color:#092e6a;font:800 23px/1.15 'Plus Jakarta Sans';letter-spacing:-.04em}.featured-card p{margin:13px 0 0;color:#5e7c9f;font-size:14px;line-height:1.7}.featured-card:after{position:absolute;right:19px;bottom:-49px;color:#1768d10d;font:900 150px/.8 'Plus Jakarta Sans';content:'✦'}@media(max-width:800px){.featured-wrap{width:calc(100% - 36px)}.featured-hero{padding:52px 0 60px}.featured-hero-grid{grid-template-columns:1fr;gap:30px}.featured-hero h1{font-size:45px}.featured-body{padding:48px 0 62px}.featured-head{display:block}.featured-head p{margin-top:15px}.featured-grid{grid-template-columns:1fr}.featured-card{min-height:250px}.featured-card h3{margin-top:50px}}
</style>
<main class="featured-page"><section class="featured-hero"><div class="featured-wrap featured-hero-grid"><div><p class="featured-kicker">PENDIDIKAN SIMUPA</p><h1>Program unggulan untuk pengalaman belajar yang lebih luas.</h1><p>Program pengembangan yang memperkuat kompetensi siswa, membuka jejaring, dan membawa pembelajaran vokasi lebih dekat dengan dunia kerja serta dunia global.</p></div><div class="featured-stat"><b>03+</b><span>Program penguatan pembelajaran yang terus berkembang bersama kebutuhan siswa dan mitra sekolah.</span></div></div></section><section class="featured-body"><div class="featured-wrap"><header class="featured-head"><div><small>PROGRAM UNGGULAN</small><h2>Belajar, berjejaring, dan bertumbuh.</h2></div><p>Setiap program memberi ruang bagi siswa untuk menghasilkan karya, membangun pengalaman, dan mengenal peluang setelah lulus.</p></header><div class="featured-grid"><article class="featured-card"><span class="featured-icon">Te</span><h3>Teaching Factory</h3><p>Pembelajaran berbasis produksi dan layanan nyata. Siswa berlatih mengikuti alur kerja profesional, dari perencanaan hingga hasil karya.</p></article><article class="featured-card"><span class="featured-icon">↗</span><h3>Go Internasional</h3><p>Penguatan bahasa, wawasan lintas budaya, dan kesiapan global agar siswa berani melanjutkan pendidikan maupun berkarya di lingkungan internasional.</p></article><article class="featured-card"><span class="featured-icon">✦</span><h3>Penguatan Karakter</h3><p>Pembiasaan nilai keislaman, kepemimpinan, kepedulian lingkungan, dan kerja sama yang hadir dalam kegiatan belajar sehari-hari.</p></article></div></div></section></main>
@endsection
