@extends('layouts.school')

@section('title', 'Sambutan Kepala Sekolah')

@section('content')
<style>
.welcome-page{background:#f6fbff;color:#092e6a}.welcome-wrap{width:min(1040px,calc(100% - 40px));margin:auto}.welcome-hero{position:relative;overflow:hidden;padding:72px 0 80px;background:linear-gradient(125deg,#092e6a,#104f9d);color:#fff}.welcome-hero:after{position:absolute;right:-95px;bottom:-245px;width:510px;height:510px;border:62px solid #ffffff13;border-radius:50%;content:''}.welcome-hero-grid{position:relative;z-index:1;display:grid;grid-template-columns:1fr 290px;align-items:center;gap:65px}.welcome-kicker{margin:0;color:#ffd248;font:800 11px 'DM Sans';letter-spacing:.2em}.welcome-hero h1{max-width:600px;margin:16px 0 18px;font:800 clamp(43px,5vw,65px)/1.04 'Plus Jakarta Sans';letter-spacing:-.06em}.welcome-hero p{margin:0;color:#d5e8ff;font-size:16px;line-height:1.7}.welcome-photo{display:grid;min-height:280px;place-items:center;border:1px dashed #ffffff75;border-radius:26px;background:#ffffff10;text-align:center}.welcome-photo span{display:grid;place-items:center;width:65px;height:65px;border-radius:50%;background:#ffffff20;color:#ffd248;font:800 20px 'Plus Jakarta Sans'}.welcome-photo small{display:block;margin-top:13px;color:#d5e8ff;font:700 11px 'DM Sans';letter-spacing:.12em}.welcome-body{display:grid;grid-template-columns:1fr 250px;gap:72px;padding:62px 0 86px}.welcome-content{color:#46698f;font-size:17px;line-height:1.88}.welcome-content p{margin:0 0 25px}.welcome-salutation{color:#092e6a;font:800 24px 'Plus Jakarta Sans'}.welcome-sign{padding:23px;border-left:3px solid #ffd248;background:#fff;border-radius:0 18px 18px 0;box-shadow:0 12px 28px #0a42790d}.welcome-sign small{color:#1768d1;font:800 10px 'DM Sans';letter-spacing:.15em}.welcome-sign strong{display:block;margin-top:8px;color:#092e6a;font:800 17px 'Plus Jakarta Sans'}.welcome-sign p{margin:5px 0 0;color:#6380a3;font-size:13px;line-height:1.55}@media(max-width:800px){.welcome-wrap{width:calc(100% - 36px)}.welcome-hero{padding:54px 0 60px}.welcome-hero-grid,.welcome-body{grid-template-columns:1fr;gap:30px}.welcome-hero h1{font-size:45px}.welcome-photo{min-height:180px}.welcome-body{padding:45px 0 62px}.welcome-content{font-size:16px}}
</style>
<style>.welcome-hero-grid>div:first-child>p:not(.welcome-kicker){display:none}.welcome-photo{border-style:solid;background:#dce5ed url('{{ asset('images/landing/kepala-sekolah-nunung-nuryati.png') }}') center 18%/cover no-repeat}.welcome-photo>div{display:none}.welcome-kicker,.welcome-hero h1{animation:welcomeEnter .8s cubic-bezier(.16,1,.3,1) both}.welcome-hero h1{animation-delay:.1s}.welcome-photo{animation:welcomePhoto .9s .18s cubic-bezier(.16,1,.3,1) both}.welcome-content,.welcome-sign{opacity:0;transform:translateY(26px);transition:opacity .7s cubic-bezier(.16,1,.3,1),transform .7s cubic-bezier(.16,1,.3,1)}.welcome-content.is-visible,.welcome-sign.is-visible{opacity:1;transform:none}@keyframes welcomeEnter{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:none}}@keyframes welcomePhoto{from{opacity:0;transform:translateX(28px) scale(.96)}to{opacity:1;transform:none}}@media(max-width:800px){.welcome-photo{min-height:410px;background-size:contain;background-position:center center}.welcome-hero-grid{gap:24px}}@media(prefers-reduced-motion:reduce){.welcome-kicker,.welcome-hero h1,.welcome-photo{animation:none}.welcome-content,.welcome-sign{opacity:1;transform:none;transition:none}}</style>
<main class="welcome-page"><section class="welcome-hero"><div class="welcome-wrap welcome-hero-grid"><div><p class="welcome-kicker">TENTANG SEKOLAH</p><h1>Sambutan Kepala Sekolah</h1><p>Assalamu’alaikum warahmatullahi wabarakatuh</p></div><div class="welcome-photo" aria-label="Area foto kepala sekolah"><div><span>NN</span><small>FOTO KEPALA SEKOLAH</small></div></div></div></section><section class="welcome-wrap welcome-body"><article class="welcome-content"><p class="welcome-salutation">Assalamu’alaikum warahmatullahi wabarakatuh,</p><p>Puji syukur kita panjatkan ke hadirat Allah Subhanahu wa Ta’ala atas limpahan rahmat, taufik, dan hidayah-Nya, sehingga SMK Muhammadiyah 4 Cileungsi dapat terus berkembang dan berkiprah dalam mencetak generasi muda yang beriman, berakhlak mulia, serta kompeten di bidangnya.</p><p>SMK Muhammadiyah 4 Cileungsi berdiri dengan tekad kuat untuk menjadi lembaga pendidikan yang tidak hanya menyiapkan peserta didik agar siap kerja, siap wirausaha, dan siap melanjutkan pendidikan, tetapi juga membentuk pribadi yang cerdas rohani, tangguh kompetensi, dan peduli terhadap lingkungan serta sosial kemasyarakatan.</p><p>Dengan mengusung visi “Sekolah Islam yang menumbuhkan Kader Cerdas Rohani, Tangguh Kompetensi, dan Lestari Aksi”, sekolah ini berkomitmen mengintegrasikan pendidikan karakter, keagamaan, dan keterampilan dalam setiap kegiatan pembelajaran.</p><p>Kami juga menjalin kerja sama strategis dengan dunia industri, dunia usaha, serta institusi pendidikan tinggi agar siswa memperoleh pengalaman nyata dan siap bersaing di dunia kerja. Selain itu, keberadaan asrama menjadi sarana pembinaan karakter islami yang mendalam, membentuk disiplin, kemandirian, dan kepedulian sosial pada diri siswa.</p><p>Akhir kata, semoga melalui profil ini para pembaca dapat mengenal lebih dekat SMK Muhammadiyah 4 Cileungsi sebagai sekolah yang berkomitmen membentuk generasi unggul, beriman, dan berdaya saing tinggi.</p><p class="welcome-salutation">Wassalamu’alaikum warahmatullahi wabarakatuh.</p></article><aside class="welcome-sign"><small>KEPALA SEKOLAH</small><strong>Nunung Nuryati, S.Pd.</strong><p>SMK Muhammadiyah 4 Cileungsi</p></aside></section></main>
<style>@media(max-width:800px){.welcome-photo{min-height:270px;background-size:cover;background-position:50% 14%}}</style>
<script>const welcomeObserver=new IntersectionObserver((entries,observer)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.14});document.querySelectorAll('.welcome-content,.welcome-sign').forEach((element,index)=>{element.style.transitionDelay=`${index*110}ms`;welcomeObserver.observe(element)});</script>
@endsection
