@extends('layouts.school')

@section('title', 'Sejarah Sekolah')

@section('content')
<style>
.history-page{background:#f6fbff;color:#092e6a}.history-wrap{width:min(1060px,calc(100% - 40px));margin:auto}.history-hero{position:relative;overflow:hidden;padding:72px 0;background:linear-gradient(125deg,#edf8ff,#dceeff)}.history-hero:after{position:absolute;right:-100px;bottom:-220px;width:520px;height:520px;border:65px solid #1d70be25;border-radius:50%;content:''}.history-hero-grid{position:relative;z-index:1;display:grid;grid-template-columns:1fr .9fr;align-items:center;gap:64px}.history-kicker{margin:0;color:#1768d1;font:800 11px 'DM Sans';letter-spacing:.2em}.history-hero h1{margin:15px 0;color:#092e6a;font:800 clamp(43px,5vw,66px)/1.03 'Plus Jakarta Sans';letter-spacing:-.06em}.history-hero p{max-width:570px;margin:0;color:#54739a;font-size:16px;line-height:1.75}.history-year{display:grid;place-items:center;min-height:230px;border:1px solid #cbe3f9;border-radius:27px;background:#fff;box-shadow:0 18px 38px #0a427912}.history-year b{display:block;color:#092e6a;font:800 76px/1 'Plus Jakarta Sans';letter-spacing:-.07em}.history-year span{display:block;margin-top:8px;color:#1768d1;font:800 10px 'DM Sans';letter-spacing:.16em;text-align:center}.history-body{display:grid;grid-template-columns:minmax(0,1fr) 255px;gap:68px;padding:66px 0 88px}.history-copy{color:#476990;font-size:17px;line-height:1.9}.history-copy p{margin:0 0 27px}.history-copy strong{color:#092e6a}.history-timeline{position:sticky;top:118px;align-self:start;padding:24px;border-left:2px solid #b9daf6;background:#fff;border-radius:0 20px 20px 0;box-shadow:0 12px 28px #0a42790c}.history-timeline h2{margin:0 0 18px;color:#1768d1;font:800 10px 'DM Sans';letter-spacing:.17em}.history-timeline div{position:relative;padding:0 0 18px 18px;color:#50749d;font-size:13px;line-height:1.5}.history-timeline div:before{position:absolute;top:4px;left:-6px;width:10px;height:10px;border:2px solid #1768d1;border-radius:50%;background:#fff;content:''}.history-timeline div:last-child{padding-bottom:0}.history-timeline b{display:block;color:#092e6a;font:800 15px 'Plus Jakarta Sans'}@media(max-width:800px){.history-wrap{width:calc(100% - 36px)}.history-hero{padding:54px 0}.history-hero-grid,.history-body{grid-template-columns:1fr;gap:30px}.history-hero h1{font-size:45px}.history-year{min-height:170px}.history-year b{font-size:62px}.history-body{padding:46px 0 62px}.history-copy{font-size:16px}.history-timeline{position:static}}
</style>
<main class="history-page"><section class="history-hero"><div class="history-wrap history-hero-grid"><div><p class="history-kicker">TENTANG SEKOLAH</p><h1>Sejarah SMK Muhammadiyah 4 Cileungsi</h1><p>Perjalanan membangun akses pendidikan yang berkarakter, relevan dengan kebutuhan zaman, dan memberi manfaat bagi masyarakat.</p></div><div class="history-year"><div><b>2012</b><span>TAHUN BERDIRI</span></div></div></div></section><section class="history-wrap history-body"><article class="history-copy"><p>SMK Muhammadiyah 4 Cileungsi berdiri sebagai wujud nyata dari komitmen <strong>Pimpinan Cabang Muhammadiyah Cileungsi</strong> dalam memberikan pelayanan terbaik kepada masyarakat, khususnya di bidang pendidikan. Melihat pentingnya peningkatan kualitas sumber daya manusia, sekolah ini hadir untuk membuka akses pendidikan kejuruan yang lebih luas dengan berbagai kompetensi keahlian yang relevan dengan kebutuhan zaman.</p><p>Pada awal berdirinya tahun 2012, sekolah hanya membuka satu kompetensi keahlian, yaitu Tata Busana. Setahun kemudian, menyusul dibukanya program Tata Boga yang semakin memperkaya pilihan bagi calon siswa. Melihat potensi besar di bidang kesehatan serta dukungan fasilitas klinik yang telah dimiliki PCM, pada tahun 2016 sekolah kembali melakukan pengembangan dengan membuka program Keperawatan dan Farmasi Klinis.</p><p>Perjalanan sekolah tidak selalu mudah. Sejak berdiri, kegiatan belajar mengajar telah menempati tiga lokasi berbeda. Dari tempat yang sangat sederhana di awal berdirinya, kini sekolah telah memiliki gedung sendiri yang representatif, lengkap dengan sarana dan prasarana pembelajaran yang memadai.</p><p>Meskipun tergolong sebagai sekolah termuda di lingkungan perguruan Muhammadiyah Cileungsi, prestasi yang diraih tidak kalah membanggakan. Siswa-siswi telah beberapa kali menorehkan prestasi di tingkat daerah maupun nasional. Sekolah juga berhasil membuka peluang bagi para alumni untuk melanjutkan kuliah sekaligus bekerja di Jepang, sebuah terobosan yang menjadi kebanggaan tersendiri.</p><p>Hingga kini, sekolah terus memperkuat jaringan kerja sama dengan dunia industri, lembaga pendidikan dalam dan luar negeri, guna menjamin kualitas pembelajaran serta penyaluran lulusan. Kami percaya, pendidikan bukan sekadar mencetak tenaga kerja terampil, tetapi membentuk insan yang berakhlak mulia, bertakwa, berkompeten, peduli terhadap lingkungan, dan mampu memberikan manfaat di mana pun mereka berada.</p></article><aside class="history-timeline"><h2>PERJALANAN SINGKAT</h2><div><b>2012</b>Tata Busana menjadi kompetensi keahlian pertama.</div><div><b>2013</b>Tata Boga dibuka untuk memperluas pilihan belajar.</div><div><b>2016</b>Keperawatan dan Farmasi Klinis mulai dikembangkan.</div><div><b>Sekarang</b>Penguatan industri, pendidikan tinggi, dan jejaring internasional.</div></aside></section></main>
@endsection
