@extends(auth()->user()?->hasRole('kepala_sekolah') ? 'layouts.kepala-sekolah' : (auth()->user()?->hasRole('panitia') ? 'layouts.panitia' : (auth()->user()?->hasRole('bendahara') ? 'layouts.bendahara' : 'layouts.admin')))

@section('title', 'Hasil Kegiatan Promosi')
@section('page_title', 'Hasil Kegiatan Promosi')
@section('page_description', 'Daftar siswa yang mengisi formulir saat kegiatan promosi sekolah.')

@section('content')
@php
    $role = auth()->user()?->hasRole('kepala_sekolah') ? 'kepala' : (auth()->user()?->hasRole('panitia') ? 'panitia' : (auth()->user()?->hasRole('bendahara') ? 'bendahara' : 'admin'));
    $prefix = $role === 'kepala' ? 'kepala-sekolah.' : ($role === 'panitia' ? 'panitia.' : ($role === 'bendahara' ? 'bendahara.' : 'admin.'));
    $canDelete = $role === 'admin';
    $theme = [
        'admin' => ['hero' => 'from-[#0b3b83] via-[#155fc0] to-[#0a2f6a]', 'soft' => 'bg-blue-50 border-blue-100', 'strong' => 'bg-blue-700 hover:bg-blue-800', 'text' => 'text-blue-700'],
        'panitia' => ['hero' => 'from-[#45218f] via-[#6933c5] to-[#351373]', 'soft' => 'bg-violet-50 border-violet-100', 'strong' => 'bg-violet-700 hover:bg-violet-800', 'text' => 'text-violet-700'],
        'bendahara' => ['hero' => 'from-[#854600] via-[#b66a0b] to-[#6d3600]', 'soft' => 'bg-amber-50 border-amber-100', 'strong' => 'bg-amber-600 hover:bg-amber-700', 'text' => 'text-amber-700'],
        'kepala' => ['hero' => 'from-[#075f62] via-[#0c8583] to-[#064c54]', 'soft' => 'bg-teal-50 border-teal-100', 'strong' => 'bg-teal-700 hover:bg-teal-800', 'text' => 'text-teal-700'],
    ][$role];
    $todayCount = $interests->getCollection()->filter(fn ($interest) => $interest->submitted_at?->isToday())->count();
@endphp

<div class="mx-auto max-w-[1320px] space-y-5">
    <section class="relative overflow-hidden rounded-[28px] bg-gradient-to-br {{ $theme['hero'] }} px-6 py-7 text-white shadow-[0_18px_45px_rgba(15,23,42,.16)] sm:px-8 sm:py-8">
        <div class="absolute -right-20 -top-24 h-60 w-60 rounded-full border border-white/15"></div><div class="absolute -bottom-28 right-36 h-52 w-52 rounded-full border border-white/10"></div>
        <div class="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div class="max-w-2xl"><p class="text-[11px] font-black uppercase tracking-[.2em] text-white/70">Rekap kegiatan sekolah</p><h2 class="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Hasil Kegiatan Promosi</h2><p class="mt-2 text-sm leading-6 text-white/80">Pantau data siswa yang mengisi formulir saat tim memperkenalkan SMK Muhammadiyah 4 Cileungsi.</p></div><div class="flex gap-3"><div class="min-w-[116px] rounded-2xl border border-white/15 bg-white/10 px-4 py-3 backdrop-blur-sm"><p class="text-[10px] font-bold uppercase tracking-wider text-white/65">Total data</p><p class="mt-1 text-2xl font-black">{{ $interests->total() }}</p></div><div class="min-w-[116px] rounded-2xl border border-white/15 bg-white/10 px-4 py-3 backdrop-blur-sm"><p class="text-[10px] font-bold uppercase tracking-wider text-white/65">Hari ini</p><p class="mt-1 text-2xl font-black">{{ $todayCount }}</p></div></div></div>
    </section>

    <section data-no-auto-tools class="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-[0_10px_28px_rgba(15,23,42,.06)]">
        <div class="flex flex-col gap-4 border-b border-slate-100 p-5 lg:flex-row lg:items-center lg:justify-between"><div><h3 class="text-lg font-black text-slate-900">Daftar pengisi formulir</h3><p class="mt-1 text-sm text-slate-500">Gunakan pencarian untuk menemukan data siswa dengan cepat.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('promosi.minat.create') }}" target="_blank" class="inline-flex items-center gap-2 rounded-xl border {{ $theme['soft'] }} px-4 py-2.5 text-sm font-black {{ $theme['text'] }} transition hover:brightness-95">Buka formulir ↗</a><a href="{{ route($prefix.'promosi-minat.export', request()->only('search')) }}" class="inline-flex items-center gap-2 rounded-xl {{ $theme['strong'] }} px-4 py-2.5 text-sm font-black text-white shadow-sm transition">↓ Export Excel</a></div></div>
        <div class="flex flex-col gap-3 border-b border-slate-100 bg-slate-50/70 p-4 sm:flex-row sm:items-center sm:justify-between"><form method="GET" class="flex flex-1 flex-col gap-2 sm:flex-row"><input type="hidden" name="per_page" value="{{ request('per_page', 10) }}"><x-list-search name="search" :value="request('search')" class="flex-1" placeholder="Cari nama, nomor WhatsApp, media sosial, SMP/MTs, atau jurusan"/><button class="rounded-xl {{ $theme['strong'] }} px-5 py-3 text-sm font-black text-white shadow-sm">Cari data</button>@if(request('search'))<a href="{{ route($prefix.'promosi-minat.index', request()->only('per_page')) }}" class="rounded-xl border border-slate-200 bg-white px-5 py-3 text-center text-sm font-black text-slate-600">Reset</a>@endif</form><x-per-page-pagination :paginator="$interests" static /></div>
        <div class="overflow-x-auto"><table class="min-w-[980px] w-full text-left"><thead class="bg-slate-50 text-[11px] font-black uppercase tracking-[.1em] text-slate-500"><tr><th class="px-5 py-4">Siswa</th><th class="px-4 py-4">Kontak</th><th class="px-4 py-4">Media sosial</th><th class="px-4 py-4">SMP/MTs</th><th class="px-4 py-4">Pilihan jurusan</th><th class="px-4 py-4">Waktu isi</th>@if($canDelete)<th class="px-5 py-4 text-right">Aksi</th>@endif</tr></thead><tbody class="divide-y divide-slate-100">@forelse($interests as $interest)<tr class="transition hover:bg-slate-50/80"><td class="px-5 py-4"><p class="font-black text-slate-900">{{ $interest->full_name }}</p><p class="mt-1 text-xs font-semibold text-slate-400">Pengisi formulir</p></td><td class="px-4 py-4 font-bold text-slate-700">{{ $interest->student_phone }}</td><td class="px-4 py-4"><span class="inline-flex rounded-lg {{ $theme['soft'] }} px-2.5 py-1.5 text-xs font-bold {{ $theme['text'] }}">{{ $interest->social_media }}</span></td><td class="px-4 py-4 font-semibold text-slate-700">{{ $interest->school_name }}</td><td class="px-4 py-4"><span class="font-bold text-slate-800">{{ $interest->major_interest }}</span></td><td class="px-4 py-4"><p class="font-bold text-slate-700">{{ $interest->submitted_at?->format('d M Y') }}</p><p class="mt-1 text-xs font-semibold text-slate-400">{{ $interest->submitted_at?->format('H:i') }} WIB</p></td>@if($canDelete)<td class="px-5 py-4 text-right"><form method="POST" action="{{ route('admin.promosi-minat.destroy', $interest) }}" onsubmit="return confirm('Hapus data {{ addslashes($interest->full_name) }}?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-200 px-3 py-2 text-xs font-black text-rose-600 transition hover:bg-rose-50">Hapus</button></form></td>@endif</tr>@empty<tr><td colspan="{{ $canDelete ? 7 : 6 }}" class="px-5 py-14 text-center"><p class="font-black text-slate-500">Belum ada data yang masuk.</p><p class="mt-1 text-sm text-slate-400">Bagikan formulir saat kegiatan promosi untuk mulai mengumpulkan data.</p></td></tr>@endforelse</tbody></table></div>
        <x-per-page-pagination :paginator="$interests" />
    </section>
</div>
@endsection
