@extends('layouts.admin')
@section('title', 'Backup Database')
@section('page_title', 'Backup Database')
@section('content')
<div class="mx-auto max-w-5xl space-y-5">
    <section class="overflow-hidden rounded-3xl p-6 text-white shadow-xl sm:p-8" style="background:linear-gradient(135deg,#0b2f6e 0%,#164a9b 58%,#0f766e 100%)"><p class="text-xs font-black uppercase tracking-[.18em] text-sky-200">Pusat Keamanan Data</p><h2 class="mt-2 text-2xl font-black sm:text-3xl" style="color:#ffffff!important">Simpan titik aman sebelum mengubah sistem.</h2><p class="mt-2 max-w-2xl text-sm font-semibold leading-6 text-sky-100">Backup menyimpan salinan seluruh data SPMB. Restore mengembalikan database dari salinan tersebut.</p></section>

    <section class="grid gap-5 lg:grid-cols-2">
        <article class="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm sm:p-6"><div class="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-xl text-blue-700">↓</div><h3 class="mt-4 text-xl font-black text-slate-950">Buat backup baru</h3><p class="mt-1 text-sm leading-6 text-slate-500">Unduh file SQL berisi kondisi data saat ini.</p><a href="{{ route('admin.database-backup.download') }}" class="mt-5 inline-flex rounded-xl bg-blue-800 px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-900/20 hover:bg-blue-900">Unduh backup .sql</a></article>
        <article class="rounded-3xl border border-rose-100 bg-white p-5 shadow-sm sm:p-6"><div class="flex h-11 w-11 items-center justify-center rounded-2xl bg-rose-50 text-xl text-rose-700">↶</div><h3 class="mt-4 text-xl font-black text-slate-950">Pulihkan backup</h3><p class="mt-1 text-sm leading-6 text-slate-500">Gunakan jika ingin mengembalikan data ke versi sebelumnya.</p><form action="{{ route('admin.database-backup.restore') }}" method="POST" enctype="multipart/form-data" class="mt-5 space-y-3">@csrf<label class="block rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3"><span class="block text-xs font-black text-slate-700">Pilih file SQL</span><input type="file" name="backup_file" accept=".sql,.txt" required class="mt-2 block w-full text-sm"></label><input name="confirmation" required placeholder="Ketik KEMBALIKAN DATABASE" class="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold focus:border-rose-500 focus:outline-none"><button class="rounded-xl border border-rose-200 px-5 py-3 text-sm font-black text-rose-700 hover:bg-rose-50">Pulihkan data</button></form></article>
    </section>

    <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h3 class="text-base font-black text-slate-950">File tersimpan</h3><p class="mt-1 text-xs text-slate-500">Backup yang dibuat sebelum pemulihan juga muncul di sini.</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{{ $backups->count() }} file</span></div><div class="mt-4 divide-y divide-slate-100">@forelse($backups as $backup)<div class="flex items-center justify-between gap-3 py-3"><div><p class="text-sm font-bold text-slate-800">{{ $backup->getFilename() }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($backup->getSize()/1024, 1, ',', '.') }} KB · {{ IlluminateSupportCarbon::createFromTimestamp($backup->getMTime())->format('d M Y H:i') }}</p></div></div>@empty<p class="py-6 text-center text-sm text-slate-500">Belum ada file backup tersimpan.</p>@endforelse</div></section>
</div>
@endsection
