@extends('layouts.admin')
@section('title', 'Audit Aktivitas')
@section('page_title', 'Audit Aktivitas')
@section('content')
<div class="mx-auto max-w-[1380px] space-y-5">
    <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-black uppercase tracking-[.16em] text-blue-700">Jejak Perubahan</p><h2 class="mt-1 text-2xl font-black text-slate-950">Siapa mengubah apa, dan kapan.</h2></div><form method="GET" class="flex w-full gap-2 lg:ml-auto lg:w-[560px]"><x-list-search :value="request('search')" placeholder="Cari pelaku, pendaftar, atau perubahan" class="min-w-0 flex-1" /><button class="rounded-xl bg-blue-800 px-5 py-2.5 text-sm font-black text-white hover:bg-blue-900">Cari</button></form></div></section>

    <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[950px] text-left text-sm"><thead class="bg-slate-50 text-[11px] font-black uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Waktu</th><th class="px-5 py-4">Pelaku</th><th class="px-5 py-4">Area</th><th class="px-5 py-4">Data</th><th class="px-5 py-4">Perubahan</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($auditLogs as $log)<tr class="align-top hover:bg-slate-50/70"><td class="whitespace-nowrap px-5 py-4 text-xs font-bold text-slate-500">{{ $log->created_at?->format('d M Y · H:i') }}</td><td class="px-5 py-4 font-bold text-slate-800">{{ $log->actor?->name ?? 'Sistem' }}</td><td class="px-5 py-4"><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">{{ $log->category }}</span></td><td class="px-5 py-4"><p class="font-black text-slate-950">{{ $log->subject_label }}</p><p class="mt-1 text-xs font-semibold text-slate-500">{{ ucfirst($log->action) }}</p></td><td class="px-5 py-4 text-slate-600">@php($changes = $log->changes ?? []) @if(isset($changes['data']))<span class="text-xs font-semibold text-slate-500">Data awal dicatat</span>@elseif($changes)<details><summary class="cursor-pointer text-xs font-black text-blue-700">Lihat detail perubahan</summary><div class="mt-2 space-y-1 rounded-xl bg-slate-50 p-3 text-xs">@foreach($changes as $field => $change)<p><strong>{{ IlluminateSupportStr::headline($field) }}:</strong> {{ is_array($change) ? ($change['sebelum'] ?? '-') : '-' }} <span class="mx-1 text-slate-400">→</span> {{ is_array($change) ? ($change['sesudah'] ?? '-') : $change }}</p>@endforeach</div></details>@else<span class="text-xs font-semibold text-slate-500">Tidak ada nilai yang berubah</span>@endif</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center"><p class="font-black text-slate-700">Belum ada riwayat perubahan</p><p class="mt-1 text-sm text-slate-500">Aktivitas baru akan muncul otomatis setelah data diubah.</p></td></tr>@endforelse</tbody></table></div><x-per-page-pagination :paginator="$auditLogs" /></section>
</div>
@endsection
